set pages 50000
set lines 500
set serveroutput on
set feedback off
set echo off
set heading on
set timing off
set verify off

accept delay_seconds number prompt "Enter value for delay_seconds: "
accept sql_id        char    prompt "If looking at specific statement, enter value for sql_id: "

col elapsed_seconds format 999999999.999
col avg_elapsed_seconds format 999999999.999
col sample_seconds format 999999999.9
col sample_start format a25
col executions format 999,999,999


DECLARE
	tblexists number(38)    := 0;
	now         varchar(19) := '';
BEGIN
	dbms_output.put_line(chr(10));
	select to_char(sysdate,'YYYY-MM-DD HH24:MI:SS') into now from dual;

	select count(1)
	into   tblexists
	from   sys.dba_tables
	where  owner='JLUTSEY'
	       and table_name='SQL_ELAPSED_TIMES_1';

	IF tblexists=0
	THEN
		execute immediate 'create table JLUTSEY.SQL_ELAPSED_TIMES_1 (sql_id varchar2(13), collection_time timestamp, executions number, elapsed_time number)';
		dbms_output.put_line(now||' - Created table JLUTSEY.SQL_ELAPSED_TIMES_1');
	ELSE
		execute immediate 'truncate table JLUTSEY.SQL_ELAPSED_TIMES_1';
		dbms_output.put_line(now||' - Truncated table JLUTSEY.SQL_ELAPSED_TIMES_1');
	END IF;

	select count(1)
	into   tblexists
	from   sys.dba_tables
	where  owner='JLUTSEY'
	       and table_name='SQL_ELAPSED_TIMES_2';

	IF tblexists=0
	THEN
		execute immediate 'create table JLUTSEY.SQL_ELAPSED_TIMES_2 (sql_id varchar2(13), collection_time timestamp, executions number, elapsed_time number)';
		dbms_output.put_line(now||' - Created table JLUTSEY.SQL_ELAPSED_TIMES_2');
	ELSE
		execute immediate 'truncate table JLUTSEY.SQL_ELAPSED_TIMES_2';
		dbms_output.put_line(now||' - Truncated table JLUTSEY.SQL_ELAPSED_TIMES_2');
	END IF;
END;
/

DECLARE
	user_sql_id varchar(13) := '&&sql_id';
	now         varchar(19) := '';
BEGIN
	select to_char(sysdate,'YYYY-MM-DD HH24:MI:SS') into now from dual;

	IF user_sql_id is null
	THEN
		insert into JLUTSEY.SQL_ELAPSED_TIMES_1 (sql_id, collection_time, executions, elapsed_time)
		select   sql_id
		       , systimestamp
		       , sum(executions)
		       , sum(elapsed_time)
		from     v$sql
		where sql_id in (select sql_id from ca.elapsedtimes_sqlids)
		and    px_servers_executions=0
		group by sql_id;
		dbms_output.put_line(now||' - Gathered initial values');
	ELSE
		insert into JLUTSEY.SQL_ELAPSED_TIMES_1 (sql_id, collection_time, executions, elapsed_time)
		select   sql_id
		       , systimestamp
		       , sum(executions)
		       , sum(elapsed_time)
		from     v$sql
		where    px_servers_executions=0
		         and sql_id=user_sql_id
		group by sql_id;
		dbms_output.put_line(now||' - Gathered initial values for sql_id '||user_sql_id);
	END IF;
	commit;

	select to_char(sysdate,'YYYY-MM-DD HH24:MI:SS') into now from dual;
	dbms_output.put_line(now||' - Waiting for the specified delay of '||trim(&&delay_seconds)||' seconds...');
END;
/

execute dbms_lock.sleep(&&delay_seconds);

DECLARE
	user_sql_id varchar(13) := '&&sql_id';
	now         varchar(19) := '';
BEGIN
	select to_char(sysdate,'YYYY-MM-DD HH24:MI:SS') into now from dual;

	IF user_sql_id is null
	THEN
		insert into JLUTSEY.SQL_ELAPSED_TIMES_2 (sql_id, collection_time, executions, elapsed_time)
		select   sql_id
		       , systimestamp
		       , sum(executions)
		       , sum(elapsed_time)
		from     v$sql
		where sql_id in (select sql_id from ca.elapsedtimes_sqlids)
		and    px_servers_executions=0
		group by sql_id;
		dbms_output.put_line(now||' - Gathered final values');
	ELSE
		insert into JLUTSEY.SQL_ELAPSED_TIMES_2 (sql_id, collection_time, executions, elapsed_time)
		select   sql_id
		       , systimestamp
		       , sum(executions)
		       , sum(elapsed_time)
		from     v$sql
		where    px_servers_executions=0
		         and sql_id=user_sql_id
		group by sql_id;
		dbms_output.put_line(now||' - Gathered final values for sql_id '||user_sql_id);
	END IF;
	commit;
END;
/

set feedback on
select     b.sql_id
         , (b.elapsed_time - a.elapsed_time) / 1000000 elapsed_seconds
         , (b.elapsed_time - a.elapsed_time) / 1000000 / (b.executions - a.executions) avg_elapsed_seconds
         , b.executions - a.executions executions
         , extract(day from (b.collection_time-a.collection_time))*86400 + 
           extract(hour from (b.collection_time-a.collection_time))*3600 + 
           extract(minute from (b.collection_time-a.collection_time))*60 + 
           extract(second from (b.collection_time-a.collection_time)) sample_seconds
         , to_char(a.collection_time,'YYYY-MM-DD HH24:MI:SS') sample_start
         , to_char(b.collection_time,'YYYY-MM-DD HH24:MI:SS') sample_end
from       jlutsey.sql_elapsed_times_1 a
join       jlutsey.sql_elapsed_times_2 b on b.sql_id=a.sql_id
where      a.executions<b.executions
union all
select     b.sql_id
         , b.elapsed_time / 1000000 elapsed_seconds
         , b.elapsed_time / 1000000 / b.executions avg_elapsed_seconds
         , b.executions executions
         , null sample_seconds
         , 'no new executions' sample_start
         , to_char(b.collection_time,'YYYY-MM-DD HH24:MI:SS') sample_end
from       jlutsey.sql_elapsed_times_1 a
right join jlutsey.sql_elapsed_times_2 b on b.sql_id=a.sql_id
where      (  a.sql_id is null
              or a.executions=b.executions
           )
           and b.executions>0
union all
select     b.sql_id
         , b.elapsed_time / 1000000 elapsed_seconds
         , b.elapsed_time / 1000000 / b.executions avg_elapsed_seconds
         , b.executions executions
         , null sample_seconds
         , 're-loaded during sample' sample_start
         , to_char(b.collection_time,'YYYY-MM-DD HH24:MI:SS') sample_end
from       jlutsey.sql_elapsed_times_1 a
right join jlutsey.sql_elapsed_times_2 b on b.sql_id=a.sql_id
where      (  a.sql_id is null
              or a.executions>b.executions
           )
           and b.executions>0
union all
select     sql_id
         , sum(elapsed_time) / 1000000 elapsed_seconds
         , sum(elapsed_time) / 1000000 / sum(executions) avg_elapsed_seconds
         , sum(executions)
         , null sample_seconds
         , 'parallel executions' sample_start
         , to_char(sysdate,'YYYY-MM-DD HH24:MI:SS') sample_end
from       v$sql
where      px_servers_executions>0
           and executions>0
           and sql_id in (select sql_id from ca.elapsedtimes_sqlids)
group by   sql_id
order by   AVG_ELAPSED_SECONDS desc
-- order by   elapsed_seconds desc
fetch next 100 rows only;




undefine delay_seconds;
undefine sql_id;



/*

delete from ca.elapsedtimes_sqlids;
insert all
	into ca.elapsedtimes_sqlids (sql_id) values ('dcux5wf9rc017')
	into ca.elapsedtimes_sqlids (sql_id) values ('dwsyfpg1yc27p')
	into ca.elapsedtimes_sqlids (sql_id) values ('f2cnc2qrmh2f6')
	into ca.elapsedtimes_sqlids (sql_id) values ('7fs9mcxfjc2jr')
	into ca.elapsedtimes_sqlids (sql_id) values ('grk31buvts41k')
	into ca.elapsedtimes_sqlids (sql_id) values ('aaq8zn3cb055v')
	into ca.elapsedtimes_sqlids (sql_id) values ('9b8nxvzk0c580')
	into ca.elapsedtimes_sqlids (sql_id) values ('f9krg0x48c5kg')
	into ca.elapsedtimes_sqlids (sql_id) values ('96rjds8g2n8tt')
	into ca.elapsedtimes_sqlids (sql_id) values ('12t22j28dn8zp')
	into ca.elapsedtimes_sqlids (sql_id) values ('3dumnukpp0an9')
	into ca.elapsedtimes_sqlids (sql_id) values ('d6jgwf7w44b0h')
	into ca.elapsedtimes_sqlids (sql_id) values ('91950x9dmsb12')
	into ca.elapsedtimes_sqlids (sql_id) values ('5m82dj11d4bn8')
	into ca.elapsedtimes_sqlids (sql_id) values ('3x149anfmnc42')
	into ca.elapsedtimes_sqlids (sql_id) values ('1w60napwysfjx')
	into ca.elapsedtimes_sqlids (sql_id) values ('gj4usg9wvnfu3')
	into ca.elapsedtimes_sqlids (sql_id) values ('br0wrtxzd0hdj')
	into ca.elapsedtimes_sqlids (sql_id) values ('7d08hn2xchjzp')
	into ca.elapsedtimes_sqlids (sql_id) values ('g6d9hxsfb0kmp')
	into ca.elapsedtimes_sqlids (sql_id) values ('8a2ybaa1gnkq1')
	into ca.elapsedtimes_sqlids (sql_id) values ('8w35zkns9smt2')
	into ca.elapsedtimes_sqlids (sql_id) values ('56hc88v1hcnwk')
	into ca.elapsedtimes_sqlids (sql_id) values ('b0t8tcg0k4pny')
	into ca.elapsedtimes_sqlids (sql_id) values ('bc8su0ty1npt8')
	into ca.elapsedtimes_sqlids (sql_id) values ('2kcmkmr5gsshj')
	into ca.elapsedtimes_sqlids (sql_id) values ('6832nb5xh8u84')
	into ca.elapsedtimes_sqlids (sql_id) values ('08cp9fmm6cv0n')
	into ca.elapsedtimes_sqlids (sql_id) values ('dvmjswkprsw2w')
	into ca.elapsedtimes_sqlids (sql_id) values ('1r9sftuxsnw31')
	into ca.elapsedtimes_sqlids (sql_id) values ('asu1mz9s1nxwd')
	into ca.elapsedtimes_sqlids (sql_id) values ('6q7s1r2c18ym9')
	into ca.elapsedtimes_sqlids (sql_id) values ('c582j2tc78zmj')
	into ca.elapsedtimes_sqlids (sql_id) values ('gbyzdp6gwd02c')
	into ca.elapsedtimes_sqlids (sql_id) values ('8924vd1cc91cr')
	into ca.elapsedtimes_sqlids (sql_id) values ('9rmhpp0bj91hn')
	into ca.elapsedtimes_sqlids (sql_id) values ('0k42sdr5nx201')
	into ca.elapsedtimes_sqlids (sql_id) values ('f6q72nrbr932a')
	into ca.elapsedtimes_sqlids (sql_id) values ('5y3c1qffjp42k')
	into ca.elapsedtimes_sqlids (sql_id) values ('bz52pz5aht4f1')
	into ca.elapsedtimes_sqlids (sql_id) values ('7p91vdvyxp54k')
	into ca.elapsedtimes_sqlids (sql_id) values ('85d1nzb7995k6')
	into ca.elapsedtimes_sqlids (sql_id) values ('520mkxqpf15q8')
	into ca.elapsedtimes_sqlids (sql_id) values ('27s77bt3pj653')
	into ca.elapsedtimes_sqlids (sql_id) values ('8axwjt3jat8fc')
	into ca.elapsedtimes_sqlids (sql_id) values ('39rct6gtk98su')
	into ca.elapsedtimes_sqlids (sql_id) values ('fbcfuk5wpt99b')
	into ca.elapsedtimes_sqlids (sql_id) values ('9t0aspmgw59jy')
	into ca.elapsedtimes_sqlids (sql_id) values ('4mn1c55kr9a0q')
	into ca.elapsedtimes_sqlids (sql_id) values ('amph8u1rhxbu7')
	into ca.elapsedtimes_sqlids (sql_id) values ('d8ns2d5h59fks')
	into ca.elapsedtimes_sqlids (sql_id) values ('3vu9p66qw1g1x')
	into ca.elapsedtimes_sqlids (sql_id) values ('6y9fv8bvadg4j')
	into ca.elapsedtimes_sqlids (sql_id) values ('bnf57hbbytgk9')
	into ca.elapsedtimes_sqlids (sql_id) values ('606s0r3hnthc3')
	into ca.elapsedtimes_sqlids (sql_id) values ('6zb7barg19hra')
	into ca.elapsedtimes_sqlids (sql_id) values ('3uqs5n7d6xpty')
	into ca.elapsedtimes_sqlids (sql_id) values ('65016939cjq1u')
	into ca.elapsedtimes_sqlids (sql_id) values ('g32m0km1njq34')
	into ca.elapsedtimes_sqlids (sql_id) values ('gdyw8pu1t5ra9')
	into ca.elapsedtimes_sqlids (sql_id) values ('grdvjpx059rjq')
	into ca.elapsedtimes_sqlids (sql_id) values ('07a2mnnbmxs1j')
	into ca.elapsedtimes_sqlids (sql_id) values ('d445h11mytt0k')
	into ca.elapsedtimes_sqlids (sql_id) values ('d4t1rd8589t3v')
	into ca.elapsedtimes_sqlids (sql_id) values ('113b6f1mxjt43')
	into ca.elapsedtimes_sqlids (sql_id) values ('1hw01r952ptpf')
	into ca.elapsedtimes_sqlids (sql_id) values ('c4h4948ya9v7s')
	into ca.elapsedtimes_sqlids (sql_id) values ('ffk5226rg9vtw')
	into ca.elapsedtimes_sqlids (sql_id) values ('6wuty3wz0xw0c')
	into ca.elapsedtimes_sqlids (sql_id) values ('0zxwd2051jw4u')
	into ca.elapsedtimes_sqlids (sql_id) values ('gbrt9ry1f5wz7')
	into ca.elapsedtimes_sqlids (sql_id) values ('cfrvud2fdjx12')
	into ca.elapsedtimes_sqlids (sql_id) values ('07uhd6uma5xn6')
	into ca.elapsedtimes_sqlids (sql_id) values ('anq2z8nn15xv0')
	into ca.elapsedtimes_sqlids (sql_id) values ('fb85a2240jyrn')
	into ca.elapsedtimes_sqlids (sql_id) values ('638k68gua9z6y')
	into ca.elapsedtimes_sqlids (sql_id) values ('5km1a29hhf2dj')
	into ca.elapsedtimes_sqlids (sql_id) values ('dawxs8r8022kc')
	into ca.elapsedtimes_sqlids (sql_id) values ('bztsqhwvpk333')
	into ca.elapsedtimes_sqlids (sql_id) values ('1rgxybpgzq33h')
	into ca.elapsedtimes_sqlids (sql_id) values ('3hydrw0bxk3f2')
	into ca.elapsedtimes_sqlids (sql_id) values ('6q03zx0t4a3y2')
	into ca.elapsedtimes_sqlids (sql_id) values ('bfkt1txhzy4yj')
	into ca.elapsedtimes_sqlids (sql_id) values ('dta1n3rx2q4yv')
	into ca.elapsedtimes_sqlids (sql_id) values ('9357ntgcyq5qz')
	into ca.elapsedtimes_sqlids (sql_id) values ('312am3mvma68s')
	into ca.elapsedtimes_sqlids (sql_id) values ('0927q8yzdy7kk')
	into ca.elapsedtimes_sqlids (sql_id) values ('d9hx5g4v867ph')
	into ca.elapsedtimes_sqlids (sql_id) values ('6f2a8f8yzy93a')
	into ca.elapsedtimes_sqlids (sql_id) values ('19rt4yhph29gb')
	into ca.elapsedtimes_sqlids (sql_id) values ('a0tbssdzs69vd')
	into ca.elapsedtimes_sqlids (sql_id) values ('au4rwptqxka07')
	into ca.elapsedtimes_sqlids (sql_id) values ('4nf76gcwqkadn')
	into ca.elapsedtimes_sqlids (sql_id) values ('6ayh1bv84ybrd')
	into ca.elapsedtimes_sqlids (sql_id) values ('ap60b7w9sucnr')
	into ca.elapsedtimes_sqlids (sql_id) values ('fvzuzg49pudp2')
	into ca.elapsedtimes_sqlids (sql_id) values ('2ak51rqt6af4h')
	into ca.elapsedtimes_sqlids (sql_id) values ('ddvhc5c0cag8w')
	into ca.elapsedtimes_sqlids (sql_id) values ('6s61sbp0zyhp4')
	into ca.elapsedtimes_sqlids (sql_id) values ('8q7r1434n6kka')
	into ca.elapsedtimes_sqlids (sql_id) values ('9sfq97ymvqkws')
	into ca.elapsedtimes_sqlids (sql_id) values ('bnybwhp2b2puy')
	into ca.elapsedtimes_sqlids (sql_id) values ('1ttyxsygnyqm7')
	into ca.elapsedtimes_sqlids (sql_id) values ('chajfvg9suqsf')
	into ca.elapsedtimes_sqlids (sql_id) values ('9ut1xsx4zqqzp')
	into ca.elapsedtimes_sqlids (sql_id) values ('67gyu5gg2krk5')
	into ca.elapsedtimes_sqlids (sql_id) values ('3tmy8kp3hatav')
	into ca.elapsedtimes_sqlids (sql_id) values ('ctubzhzr6fthy')
	into ca.elapsedtimes_sqlids (sql_id) values ('8pbksnpu96wag')
	into ca.elapsedtimes_sqlids (sql_id) values ('6fshp5g2m6wq4')
	into ca.elapsedtimes_sqlids (sql_id) values ('dcj225fxgqx1g')
	into ca.elapsedtimes_sqlids (sql_id) values ('andnchgm86z2f')
	into ca.elapsedtimes_sqlids (sql_id) values ('68ssxbf1yfzhs')
	into ca.elapsedtimes_sqlids (sql_id) values ('9333ug37tg0rs')
	into ca.elapsedtimes_sqlids (sql_id) values ('bq0xzjhtx31q4')
	into ca.elapsedtimes_sqlids (sql_id) values ('9k8wdafy2b1qf')
	into ca.elapsedtimes_sqlids (sql_id) values ('502h2bfc6m1ra')
	into ca.elapsedtimes_sqlids (sql_id) values ('8qngrwrmb323u')
	into ca.elapsedtimes_sqlids (sql_id) values ('22wfpngxr745z')
	into ca.elapsedtimes_sqlids (sql_id) values ('gzcrt25xtr4f5')
	into ca.elapsedtimes_sqlids (sql_id) values ('00m2pd9kug4g7')
	into ca.elapsedtimes_sqlids (sql_id) values ('0f9p9tjmpb521')
	into ca.elapsedtimes_sqlids (sql_id) values ('d98964p38r63n')
	into ca.elapsedtimes_sqlids (sql_id) values ('593hwz9hb763x')
	into ca.elapsedtimes_sqlids (sql_id) values ('7jfpg48wqm65x')
	into ca.elapsedtimes_sqlids (sql_id) values ('2t4bg94aaz6gz')
	into ca.elapsedtimes_sqlids (sql_id) values ('3dq3yj1hx36xh')
	into ca.elapsedtimes_sqlids (sql_id) values ('9gcpft14nb7g5')
	into ca.elapsedtimes_sqlids (sql_id) values ('gc972194kv8wx')
	into ca.elapsedtimes_sqlids (sql_id) values ('gd1rdrv4sz90g')
	into ca.elapsedtimes_sqlids (sql_id) values ('2ff2nuktdzbq1')
	into ca.elapsedtimes_sqlids (sql_id) values ('a68j0xwk7md65')
	into ca.elapsedtimes_sqlids (sql_id) values ('2cz4ga72hbfjw')
	into ca.elapsedtimes_sqlids (sql_id) values ('dsqa3xz2abfpm')
	into ca.elapsedtimes_sqlids (sql_id) values ('6v4gxdmph3fpm')
	into ca.elapsedtimes_sqlids (sql_id) values ('8fx16s1dkbh1c')
	into ca.elapsedtimes_sqlids (sql_id) values ('dwu1fjma77h9j')
	into ca.elapsedtimes_sqlids (sql_id) values ('aw9kq5wttmha2')
	into ca.elapsedtimes_sqlids (sql_id) values ('fcu2rmjq0mhms')
	into ca.elapsedtimes_sqlids (sql_id) values ('649xaa82vzpzz')
	into ca.elapsedtimes_sqlids (sql_id) values ('01rr29x527qt6')
	into ca.elapsedtimes_sqlids (sql_id) values ('1qrrkkgdb3r2b')
	into ca.elapsedtimes_sqlids (sql_id) values ('0rvrsuc8ubrhy')
	into ca.elapsedtimes_sqlids (sql_id) values ('6fq4rz2h5gs1n')
	into ca.elapsedtimes_sqlids (sql_id) values ('d3bm08afgms9x')
	into ca.elapsedtimes_sqlids (sql_id) values ('0dyr903wkzssz')
	into ca.elapsedtimes_sqlids (sql_id) values ('9wdsnuc0hbsvr')
	into ca.elapsedtimes_sqlids (sql_id) values ('f43vp6z4q3vf9')
	into ca.elapsedtimes_sqlids (sql_id) values ('0bt79531ngw8m')
	into ca.elapsedtimes_sqlids (sql_id) values ('gt9v4gmk5bydx')
	into ca.elapsedtimes_sqlids (sql_id) values ('6tngkqp6dmynh')
	into ca.elapsedtimes_sqlids (sql_id) values ('ff3mqxgjavyzc')
	into ca.elapsedtimes_sqlids (sql_id) values ('b05xxg536gz0r')
	into ca.elapsedtimes_sqlids (sql_id) values ('gwcf43zjwgz51')
	into ca.elapsedtimes_sqlids (sql_id) values ('2su39rrhs7zsz')
	into ca.elapsedtimes_sqlids (sql_id) values ('3n1s2daps00kq')
	into ca.elapsedtimes_sqlids (sql_id) values ('249dw2gdhc0uc')
	into ca.elapsedtimes_sqlids (sql_id) values ('9bgq0nccuh105')
	into ca.elapsedtimes_sqlids (sql_id) values ('0z2tn88r0s13v')
	into ca.elapsedtimes_sqlids (sql_id) values ('f6jqwr5wk81jr')
	into ca.elapsedtimes_sqlids (sql_id) values ('cvk7wxb8bn1xy')
	into ca.elapsedtimes_sqlids (sql_id) values ('94bwsh9ath287')
	into ca.elapsedtimes_sqlids (sql_id) values ('ctt2xk4wa82h5')
	into ca.elapsedtimes_sqlids (sql_id) values ('c72w8y2t682n8')
	into ca.elapsedtimes_sqlids (sql_id) values ('c3hpn9c3pc2pv')
	into ca.elapsedtimes_sqlids (sql_id) values ('0jx3xczcmh3h8')
	into ca.elapsedtimes_sqlids (sql_id) values ('gnwxsp3n5s3ur')
	into ca.elapsedtimes_sqlids (sql_id) values ('254f2shz4w4hy')
	into ca.elapsedtimes_sqlids (sql_id) values ('3pxcbw26js68f')
	into ca.elapsedtimes_sqlids (sql_id) values ('bndf0amxy8aat')
	into ca.elapsedtimes_sqlids (sql_id) values ('3ntvk9gcqcab1')
	into ca.elapsedtimes_sqlids (sql_id) values ('98p7hw63d4ays')
	into ca.elapsedtimes_sqlids (sql_id) values ('6vc66wu0f0azq')
	into ca.elapsedtimes_sqlids (sql_id) values ('76h85n9d64c43')
	into ca.elapsedtimes_sqlids (sql_id) values ('0z4806xc8scja')
	into ca.elapsedtimes_sqlids (sql_id) values ('24ruunm53sf1x')
	into ca.elapsedtimes_sqlids (sql_id) values ('5zrqzxw7khf7m')
	into ca.elapsedtimes_sqlids (sql_id) values ('fk90tugawsfhs')
	into ca.elapsedtimes_sqlids (sql_id) values ('2basdgz858gfd')
	into ca.elapsedtimes_sqlids (sql_id) values ('4vm3bf1tu4gjm')
	into ca.elapsedtimes_sqlids (sql_id) values ('39ghc4wsvhgqt')
	into ca.elapsedtimes_sqlids (sql_id) values ('9gz6cx2vmcguw')
	into ca.elapsedtimes_sqlids (sql_id) values ('3t0svnjau0hj5')
	into ca.elapsedtimes_sqlids (sql_id) values ('4n9f4nk380krc')
	into ca.elapsedtimes_sqlids (sql_id) values ('4xsjcustqwmg6')
	into ca.elapsedtimes_sqlids (sql_id) values ('ca2ky6uj38mha')
	into ca.elapsedtimes_sqlids (sql_id) values ('4ddw72z75nmtc')
	into ca.elapsedtimes_sqlids (sql_id) values ('3bt172d3twnqd')
	into ca.elapsedtimes_sqlids (sql_id) values ('2xbu442558pwg')
	into ca.elapsedtimes_sqlids (sql_id) values ('9s01jbu25sq6u')
	into ca.elapsedtimes_sqlids (sql_id) values ('814sxt42t4q7q')
	into ca.elapsedtimes_sqlids (sql_id) values ('9g31anzup4q9k')
	into ca.elapsedtimes_sqlids (sql_id) values ('8d8z314u8ntpa')
	into ca.elapsedtimes_sqlids (sql_id) values ('0wtrqfzmusvm8')
	into ca.elapsedtimes_sqlids (sql_id) values ('cs0xu1tz4cvwr')
	into ca.elapsedtimes_sqlids (sql_id) values ('4c0pytjr2swgm')
	into ca.elapsedtimes_sqlids (sql_id) values ('17n1nn6a98xx5')
	into ca.elapsedtimes_sqlids (sql_id) values ('fvtnkyf6nsy2j')
	into ca.elapsedtimes_sqlids (sql_id) values ('860sgbppswya2')
	into ca.elapsedtimes_sqlids (sql_id) values ('gkvzgxyg9t08y')
	into ca.elapsedtimes_sqlids (sql_id) values ('cfw89wvhg50x0')
	into ca.elapsedtimes_sqlids (sql_id) values ('dc3wuc0ffp150')
	into ca.elapsedtimes_sqlids (sql_id) values ('bna857ugsx184')
	into ca.elapsedtimes_sqlids (sql_id) values ('a4fkdmvg252hq')
	into ca.elapsedtimes_sqlids (sql_id) values ('d7wsy28bkd2ku')
	into ca.elapsedtimes_sqlids (sql_id) values ('4y5q8jnxaj2p1')
	into ca.elapsedtimes_sqlids (sql_id) values ('cjn9z5fms55fu')
	into ca.elapsedtimes_sqlids (sql_id) values ('g2mg41rfhp86k')
	into ca.elapsedtimes_sqlids (sql_id) values ('gvw6fg4kkt86m')
	into ca.elapsedtimes_sqlids (sql_id) values ('dtmjb3x4vj9cp')
	into ca.elapsedtimes_sqlids (sql_id) values ('5cg7k7a79tbrc')
	into ca.elapsedtimes_sqlids (sql_id) values ('8numdtj7b1bwj')
	into ca.elapsedtimes_sqlids (sql_id) values ('9h90kbuhjtbz7')
	into ca.elapsedtimes_sqlids (sql_id) values ('0uk2qukq2tf8v')
	into ca.elapsedtimes_sqlids (sql_id) values ('2g8zgf9xq9fdu')
	into ca.elapsedtimes_sqlids (sql_id) values ('b4axzqz8jtg1d')
	into ca.elapsedtimes_sqlids (sql_id) values ('ghbm4u0c01jqm')
	into ca.elapsedtimes_sqlids (sql_id) values ('4j94jrxrbdjv5')
	into ca.elapsedtimes_sqlids (sql_id) values ('fap5ssc7qpkh7')
	into ca.elapsedtimes_sqlids (sql_id) values ('73rbg53fqdkpy')
	into ca.elapsedtimes_sqlids (sql_id) values ('bfdfcaa6x5pf5')
	into ca.elapsedtimes_sqlids (sql_id) values ('f84mqstr19q02')
	into ca.elapsedtimes_sqlids (sql_id) values ('0fbmxks2mdq0g')
	into ca.elapsedtimes_sqlids (sql_id) values ('by1xy9paz1quv')
	into ca.elapsedtimes_sqlids (sql_id) values ('dkfkf71q05rmu')
	into ca.elapsedtimes_sqlids (sql_id) values ('6u8301s8aps4r')
	into ca.elapsedtimes_sqlids (sql_id) values ('8s50tvktx1u11')
	into ca.elapsedtimes_sqlids (sql_id) values ('f6g6wh6ad9wuz')
	into ca.elapsedtimes_sqlids (sql_id) values ('g1qz246p1dx1v')
	into ca.elapsedtimes_sqlids (sql_id) values ('d1zx0gnzytx5d')
	into ca.elapsedtimes_sqlids (sql_id) values ('9y7bmh2m95y1k')
	into ca.elapsedtimes_sqlids (sql_id) values ('3fqsmc44yy0u9')
	into ca.elapsedtimes_sqlids (sql_id) values ('f6dq28ph9k21f')
	into ca.elapsedtimes_sqlids (sql_id) values ('1ttfcx6waf2zm')
	into ca.elapsedtimes_sqlids (sql_id) values ('27cfqmky1q3gk')
	into ca.elapsedtimes_sqlids (sql_id) values ('1dx8chbnya3mx')
	into ca.elapsedtimes_sqlids (sql_id) values ('ax9c1t5g1k3qt')
	into ca.elapsedtimes_sqlids (sql_id) values ('1qq0hu9a2a41t')
	into ca.elapsedtimes_sqlids (sql_id) values ('2kv5apf5fu44k')
	into ca.elapsedtimes_sqlids (sql_id) values ('dwa25nswr650d')
	into ca.elapsedtimes_sqlids (sql_id) values ('f6myh67xff56d')
	into ca.elapsedtimes_sqlids (sql_id) values ('6s0jw7vrh25sb')
	into ca.elapsedtimes_sqlids (sql_id) values ('fqkjm094yy674')
	into ca.elapsedtimes_sqlids (sql_id) values ('crmvywykb28wf')
	into ca.elapsedtimes_sqlids (sql_id) values ('b1kqzwpcnub14')
	into ca.elapsedtimes_sqlids (sql_id) values ('3j26y1fj82cbh')
	into ca.elapsedtimes_sqlids (sql_id) values ('d0tajfdqkqcnw')
	into ca.elapsedtimes_sqlids (sql_id) values ('6s1nhtdfdfcp9')
	into ca.elapsedtimes_sqlids (sql_id) values ('apqkacfv5ufaf')
	into ca.elapsedtimes_sqlids (sql_id) values ('b004vu0qp6j0d')
	into ca.elapsedtimes_sqlids (sql_id) values ('9n45a2kn0ykjm')
	into ca.elapsedtimes_sqlids (sql_id) values ('c7gg599rqambm')
	into ca.elapsedtimes_sqlids (sql_id) values ('5nnwm241zynt7')
	into ca.elapsedtimes_sqlids (sql_id) values ('46h54p0qs6q9t')
	into ca.elapsedtimes_sqlids (sql_id) values ('1ak30jgq7uqbu')
	into ca.elapsedtimes_sqlids (sql_id) values ('2xh1vsabwkr09')
	into ca.elapsedtimes_sqlids (sql_id) values ('as0grzz3kfsdy')
	into ca.elapsedtimes_sqlids (sql_id) values ('99dq3u7fbksux')
	into ca.elapsedtimes_sqlids (sql_id) values ('bqsh413sgqt6p')
	into ca.elapsedtimes_sqlids (sql_id) values ('bp5b1qdy1au9a')
	into ca.elapsedtimes_sqlids (sql_id) values ('19av7hg8mfuk0')
	into ca.elapsedtimes_sqlids (sql_id) values ('g3vgdgwtfyuwp')
	into ca.elapsedtimes_sqlids (sql_id) values ('063v4fzgaqv25')
	into ca.elapsedtimes_sqlids (sql_id) values ('f0k87z525yw49')
	into ca.elapsedtimes_sqlids (sql_id) values ('0y323nyhkfx05')
	into ca.elapsedtimes_sqlids (sql_id) values ('4v8nwywgtqxpn')
	into ca.elapsedtimes_sqlids (sql_id) values ('0a8vr328skxqx')
	into ca.elapsedtimes_sqlids (sql_id) values ('69bfmqa2gqyms')
	into ca.elapsedtimes_sqlids (sql_id) values ('gbq39q6z82ztd')
	into ca.elapsedtimes_sqlids (sql_id) values ('5vandvuz0r2ng')
	into ca.elapsedtimes_sqlids (sql_id) values ('dv0phd1qxz33y')
	into ca.elapsedtimes_sqlids (sql_id) values ('84j8wq8trv3vj')
	into ca.elapsedtimes_sqlids (sql_id) values ('3g77hzjbrg4nb')
	into ca.elapsedtimes_sqlids (sql_id) values ('2rchpnyj3g5kw')
	into ca.elapsedtimes_sqlids (sql_id) values ('0npzvsgwwr63n')
	into ca.elapsedtimes_sqlids (sql_id) values ('guqymk3f7b6m2')
	into ca.elapsedtimes_sqlids (sql_id) values ('djftjp3fxm84z')
	into ca.elapsedtimes_sqlids (sql_id) values ('8b1ca5mzbm8wq')
	into ca.elapsedtimes_sqlids (sql_id) values ('6u2a39r1wvdp9')
	into ca.elapsedtimes_sqlids (sql_id) values ('8j16zz43wgdx6')
	into ca.elapsedtimes_sqlids (sql_id) values ('3cawg2ggcgdzk')
	into ca.elapsedtimes_sqlids (sql_id) values ('fuk7vy5bzmfn3')
	into ca.elapsedtimes_sqlids (sql_id) values ('0ugn21xjh3fwc')
	into ca.elapsedtimes_sqlids (sql_id) values ('gh6a926r1mg67')
	into ca.elapsedtimes_sqlids (sql_id) values ('gbfjsz695rgtf')
	into ca.elapsedtimes_sqlids (sql_id) values ('axgbba2jtmhay')
	into ca.elapsedtimes_sqlids (sql_id) values ('194au92nrbk7y')
	into ca.elapsedtimes_sqlids (sql_id) values ('8c0gawwfn3n9q')
	into ca.elapsedtimes_sqlids (sql_id) values ('6hd5b3ukzgnyc')
	into ca.elapsedtimes_sqlids (sql_id) values ('91buy0tvfmp45')
	into ca.elapsedtimes_sqlids (sql_id) values ('aubxzj17f7pb0')
	into ca.elapsedtimes_sqlids (sql_id) values ('acfbb3umggpf7')
	into ca.elapsedtimes_sqlids (sql_id) values ('dy7hzx61fmpv4')
	into ca.elapsedtimes_sqlids (sql_id) values ('62crrhf6jrrty')
	into ca.elapsedtimes_sqlids (sql_id) values ('fkr7d2s4ybucy')
	into ca.elapsedtimes_sqlids (sql_id) values ('224cuk0bk3v2x')
	into ca.elapsedtimes_sqlids (sql_id) values ('4upx9q5b9rv8j')
	into ca.elapsedtimes_sqlids (sql_id) values ('98vcj366sgvgy')
	into ca.elapsedtimes_sqlids (sql_id) values ('cfsq36gxfrx94')
	into ca.elapsedtimes_sqlids (sql_id) values ('5dpadxm1cry7c')
	into ca.elapsedtimes_sqlids (sql_id) values ('75dh8ag5zc05h')
	into ca.elapsedtimes_sqlids (sql_id) values ('1pqt37ccmw0uu')
	into ca.elapsedtimes_sqlids (sql_id) values ('gcna5thbvw404')
	into ca.elapsedtimes_sqlids (sql_id) values ('9vtq8u7hcs4z1')
	into ca.elapsedtimes_sqlids (sql_id) values ('0jzby916tn5q1')
	into ca.elapsedtimes_sqlids (sql_id) values ('4rv14jmhmh71z')
	into ca.elapsedtimes_sqlids (sql_id) values ('00a90hr5ts74d')
	into ca.elapsedtimes_sqlids (sql_id) values ('3qf1s5ztan753')
	into ca.elapsedtimes_sqlids (sql_id) values ('30090m6pmh79b')
	into ca.elapsedtimes_sqlids (sql_id) values ('g6136jb9287nb')
	into ca.elapsedtimes_sqlids (sql_id) values ('d40k9hz1m07nk')
	into ca.elapsedtimes_sqlids (sql_id) values ('ftq96by7tc98f')
	into ca.elapsedtimes_sqlids (sql_id) values ('cf3pdgd5fc9v5')
	into ca.elapsedtimes_sqlids (sql_id) values ('24wvt9wrf4bmy')
	into ca.elapsedtimes_sqlids (sql_id) values ('6wg4yqud8nfw1')
	into ca.elapsedtimes_sqlids (sql_id) values ('6xmzdzfcphg1t')
	into ca.elapsedtimes_sqlids (sql_id) values ('0zk6zxzjphk4t')
	into ca.elapsedtimes_sqlids (sql_id) values ('1kbrx086gsnxg')
	into ca.elapsedtimes_sqlids (sql_id) values ('07r6gp3qgspcm')
	into ca.elapsedtimes_sqlids (sql_id) values ('5k1hk9vmahptb')
	into ca.elapsedtimes_sqlids (sql_id) values ('554apg3834pvp')
	into ca.elapsedtimes_sqlids (sql_id) values ('2v0cqvnrk4r4w')
	into ca.elapsedtimes_sqlids (sql_id) values ('g4mv2v9mrhrb5')
	into ca.elapsedtimes_sqlids (sql_id) values ('60vppq59kws2c')
	into ca.elapsedtimes_sqlids (sql_id) values ('846mux6zb4s5t')
	into ca.elapsedtimes_sqlids (sql_id) values ('6j4r28kg24s8p')
	into ca.elapsedtimes_sqlids (sql_id) values ('fk9rsscazhsjm')
	into ca.elapsedtimes_sqlids (sql_id) values ('cwxbyyrsu0sny')
	into ca.elapsedtimes_sqlids (sql_id) values ('d4mjz8d84ctyh')
	into ca.elapsedtimes_sqlids (sql_id) values ('ah72m6bbnnuar')
	into ca.elapsedtimes_sqlids (sql_id) values ('3f4zxy66xnury')
	into ca.elapsedtimes_sqlids (sql_id) values ('5hrgdva2unuwa')
	into ca.elapsedtimes_sqlids (sql_id) values ('1vpbymjk2wv08')
	into ca.elapsedtimes_sqlids (sql_id) values ('7156mj2kmcv60')
	into ca.elapsedtimes_sqlids (sql_id) values ('3zujq4y114vzd')
	into ca.elapsedtimes_sqlids (sql_id) values ('ght1dhtx54wru')
	into ca.elapsedtimes_sqlids (sql_id) values ('6sh8avsxksxpn')
	into ca.elapsedtimes_sqlids (sql_id) values ('0y324xz8yszzb')
	into ca.elapsedtimes_sqlids (sql_id) values ('gj6krfzy2szzm')
	into ca.elapsedtimes_sqlids (sql_id) values ('aqmkfst5yp1j4')
	into ca.elapsedtimes_sqlids (sql_id) values ('930bxxrvr1473')
	into ca.elapsedtimes_sqlids (sql_id) values ('2z91c3frv94qh')
	into ca.elapsedtimes_sqlids (sql_id) values ('80uuxt2a8t5ca')
	into ca.elapsedtimes_sqlids (sql_id) values ('10zuqhwf9x603')
	into ca.elapsedtimes_sqlids (sql_id) values ('a1kd9pgwdd71n')
	into ca.elapsedtimes_sqlids (sql_id) values ('6u46dmr5a97bk')
	into ca.elapsedtimes_sqlids (sql_id) values ('c0m35ntp8j8dt')
	into ca.elapsedtimes_sqlids (sql_id) values ('30tkbrd0y99qj')
	into ca.elapsedtimes_sqlids (sql_id) values ('4d4znrffbt9s6')
	into ca.elapsedtimes_sqlids (sql_id) values ('291m4x6cqdb1h')
	into ca.elapsedtimes_sqlids (sql_id) values ('66bmna1xvtb6h')
	into ca.elapsedtimes_sqlids (sql_id) values ('6xyz57r4zjc14')
	into ca.elapsedtimes_sqlids (sql_id) values ('1jmv2j6vs1cpq')
	into ca.elapsedtimes_sqlids (sql_id) values ('g5wzf4xvddct6')
	into ca.elapsedtimes_sqlids (sql_id) values ('cvqn222bbjcvy')
	into ca.elapsedtimes_sqlids (sql_id) values ('4r1m8qjjh1dth')
	into ca.elapsedtimes_sqlids (sql_id) values ('g4b6u72qttffv')
	into ca.elapsedtimes_sqlids (sql_id) values ('9t78wmrg79fur')
	into ca.elapsedtimes_sqlids (sql_id) values ('53q3wrsgkpg94')
	into ca.elapsedtimes_sqlids (sql_id) values ('26f01gu4q5jru')
	into ca.elapsedtimes_sqlids (sql_id) values ('acjp7tvynpkuc')
	into ca.elapsedtimes_sqlids (sql_id) values ('2nwzw9zmbxp4j')
	into ca.elapsedtimes_sqlids (sql_id) values ('2ktvnsk0jpp76')
	into ca.elapsedtimes_sqlids (sql_id) values ('a3d6yunbxxpsa')
	into ca.elapsedtimes_sqlids (sql_id) values ('6zjxdkb151pum')
	into ca.elapsedtimes_sqlids (sql_id) values ('4fhasfb7hjqau')
	into ca.elapsedtimes_sqlids (sql_id) values ('8w6d40x6pdqst')
	into ca.elapsedtimes_sqlids (sql_id) values ('04mk2j9c85r9w')
	into ca.elapsedtimes_sqlids (sql_id) values ('0q5yss9hd9u6v')
	into ca.elapsedtimes_sqlids (sql_id) values ('ccawc679hdu98')
	into ca.elapsedtimes_sqlids (sql_id) values ('bt9vrazt9jutz')
	into ca.elapsedtimes_sqlids (sql_id) values ('2gwm2gtyb1uzq')
	into ca.elapsedtimes_sqlids (sql_id) values ('97uhxt6da5vkq')
	into ca.elapsedtimes_sqlids (sql_id) values ('3dngnyuff9wvz')
	into ca.elapsedtimes_sqlids (sql_id) values ('c3d3cj7rujz90')
	into ca.elapsedtimes_sqlids (sql_id) values ('ad9x0nv28u0bx')
	into ca.elapsedtimes_sqlids (sql_id) values ('6yx4q3gktu0qa')
	into ca.elapsedtimes_sqlids (sql_id) values ('d16u4tfq5k0w9')
	into ca.elapsedtimes_sqlids (sql_id) values ('cz87jgyz9k16f')
	into ca.elapsedtimes_sqlids (sql_id) values ('d31v0yxnqf19a')
	into ca.elapsedtimes_sqlids (sql_id) values ('c23apk4zuq3ma')
	into ca.elapsedtimes_sqlids (sql_id) values ('8zht5pw8b65qg')
	into ca.elapsedtimes_sqlids (sql_id) values ('c8rf3ww6y26r1')
	into ca.elapsedtimes_sqlids (sql_id) values ('0sgg71703q6x3')
	into ca.elapsedtimes_sqlids (sql_id) values ('46a8wcdguk76f')
	into ca.elapsedtimes_sqlids (sql_id) values ('10r7ku925y9as')
	into ca.elapsedtimes_sqlids (sql_id) values ('dx94sqcw16anf')
	into ca.elapsedtimes_sqlids (sql_id) values ('dgbnra10wqbps')
	into ca.elapsedtimes_sqlids (sql_id) values ('4cy5w3uwdkccb')
	into ca.elapsedtimes_sqlids (sql_id) values ('746cmv45fffk8')
	into ca.elapsedtimes_sqlids (sql_id) values ('4322fy95a6gkt')
	into ca.elapsedtimes_sqlids (sql_id) values ('3jmbm6dbzygzm')
	into ca.elapsedtimes_sqlids (sql_id) values ('0tuhjm3d16j2c')
	into ca.elapsedtimes_sqlids (sql_id) values ('bwb6uj2pakj39')
	into ca.elapsedtimes_sqlids (sql_id) values ('a5c99kctsfj5y')
	into ca.elapsedtimes_sqlids (sql_id) values ('0cftwfu2t6jz0')
	into ca.elapsedtimes_sqlids (sql_id) values ('b5mh80zud6k4b')
	into ca.elapsedtimes_sqlids (sql_id) values ('fu9j4fswtqm06')
	into ca.elapsedtimes_sqlids (sql_id) values ('7ka0gg1hwqmvs')
	into ca.elapsedtimes_sqlids (sql_id) values ('g0hknym20qmzq')
	into ca.elapsedtimes_sqlids (sql_id) values ('3hy8sukywqnss')
	into ca.elapsedtimes_sqlids (sql_id) values ('1bn1sbkcpqq9c')
	into ca.elapsedtimes_sqlids (sql_id) values ('dwzbc7xspyqsp')
	into ca.elapsedtimes_sqlids (sql_id) values ('1a0btta4hfsxa')
	into ca.elapsedtimes_sqlids (sql_id) values ('1utzrx7fhqt3c')
	into ca.elapsedtimes_sqlids (sql_id) values ('gk9gucgphkv86')
	into ca.elapsedtimes_sqlids (sql_id) values ('cyt67u9t42ytd')
	into ca.elapsedtimes_sqlids (sql_id) values ('7q8a0r6n96zdp')
	into ca.elapsedtimes_sqlids (sql_id) values ('62q7ksctz6zfd')
	into ca.elapsedtimes_sqlids (sql_id) values ('9mudyv5fdm1fx')
	into ca.elapsedtimes_sqlids (sql_id) values ('62hz05zuw71mf')
	into ca.elapsedtimes_sqlids (sql_id) values ('dnw2hs0wgm2zd')
	into ca.elapsedtimes_sqlids (sql_id) values ('9mpt1c8p4r34u')
	into ca.elapsedtimes_sqlids (sql_id) values ('3pdk93z8gm3rs')
	into ca.elapsedtimes_sqlids (sql_id) values ('7dq1r7duqm44z')
	into ca.elapsedtimes_sqlids (sql_id) values ('8fbxxuh48b46a')
	into ca.elapsedtimes_sqlids (sql_id) values ('96p6f5fk7r5b9')
	into ca.elapsedtimes_sqlids (sql_id) values ('0jrjkuhbcz64c')
	into ca.elapsedtimes_sqlids (sql_id) values ('gxmb62mgjv7hp')
	into ca.elapsedtimes_sqlids (sql_id) values ('8bbk9c66zr801')
	into ca.elapsedtimes_sqlids (sql_id) values ('bkfaass6yv8r2')
	into ca.elapsedtimes_sqlids (sql_id) values ('cf8648mubbbja')
	into ca.elapsedtimes_sqlids (sql_id) values ('5za02f0bqrcq8')
	into ca.elapsedtimes_sqlids (sql_id) values ('3fs455gxnvcyh')
	into ca.elapsedtimes_sqlids (sql_id) values ('1bdzrqhf8zd6p')
	into ca.elapsedtimes_sqlids (sql_id) values ('1z4rqqz88vdcy')
	into ca.elapsedtimes_sqlids (sql_id) values ('0xzb3ppvagfgq')
	into ca.elapsedtimes_sqlids (sql_id) values ('frf17ggzkgh0x')
	into ca.elapsedtimes_sqlids (sql_id) values ('8ad0ra23z3jr4')
	into ca.elapsedtimes_sqlids (sql_id) values ('f1ghf7bbmvk1u')
	into ca.elapsedtimes_sqlids (sql_id) values ('8n8uzxav0vmq5')
	into ca.elapsedtimes_sqlids (sql_id) values ('bkn5dxqygbn1c')
	into ca.elapsedtimes_sqlids (sql_id) values ('0b1nf320n3pqb')
	into ca.elapsedtimes_sqlids (sql_id) values ('9fdd943pdvsg4')
	into ca.elapsedtimes_sqlids (sql_id) values ('2nbztgaambu1w')
	into ca.elapsedtimes_sqlids (sql_id) values ('8sy6u61v4zuua')
	into ca.elapsedtimes_sqlids (sql_id) values ('9rwfqqfw6gv99')
	into ca.elapsedtimes_sqlids (sql_id) values ('an4z573kmzvfg')
	into ca.elapsedtimes_sqlids (sql_id) values ('br6pccn2smw22')
	into ca.elapsedtimes_sqlids (sql_id) values ('cb18g845j3wt4')
	into ca.elapsedtimes_sqlids (sql_id) values ('bnckzjdfgzxnj')
	into ca.elapsedtimes_sqlids (sql_id) values ('0qf6xd83z3xzu')
	into ca.elapsedtimes_sqlids (sql_id) values ('0ygy1rdpcs0a4')
	into ca.elapsedtimes_sqlids (sql_id) values ('3fya87vcmw14v')
	into ca.elapsedtimes_sqlids (sql_id) values ('293c4ukh1s390')
	into ca.elapsedtimes_sqlids (sql_id) values ('amrnh3h2j04rr')
	into ca.elapsedtimes_sqlids (sql_id) values ('fu028ysa1c4sb')
	into ca.elapsedtimes_sqlids (sql_id) values ('71kb4gxh844tg')
	into ca.elapsedtimes_sqlids (sql_id) values ('63krgk6jbn57t')
	into ca.elapsedtimes_sqlids (sql_id) values ('7ch9a9rajw60d')
	into ca.elapsedtimes_sqlids (sql_id) values ('0uc068u11n7y3')
	into ca.elapsedtimes_sqlids (sql_id) values ('9qgy1tvgyc8b6')
	into ca.elapsedtimes_sqlids (sql_id) values ('57qn4m8r008uu')
	into ca.elapsedtimes_sqlids (sql_id) values ('g4m1g219ds9cz')
	into ca.elapsedtimes_sqlids (sql_id) values ('1np24k878nbkn')
	into ca.elapsedtimes_sqlids (sql_id) values ('15292u60thc8a')
	into ca.elapsedtimes_sqlids (sql_id) values ('cd5nq1ks94ca2')
	into ca.elapsedtimes_sqlids (sql_id) values ('dw4vgh126sdb1')
	into ca.elapsedtimes_sqlids (sql_id) values ('9x78v33fx4dcz')
	into ca.elapsedtimes_sqlids (sql_id) values ('5b0habcuvwdp4')
	into ca.elapsedtimes_sqlids (sql_id) values ('46p34993p8dru')
	into ca.elapsedtimes_sqlids (sql_id) values ('c2ukqwrkkcjwd')
	into ca.elapsedtimes_sqlids (sql_id) values ('31pqv81a4ck3w')
	into ca.elapsedtimes_sqlids (sql_id) values ('6r2v8fbq08k42')
	into ca.elapsedtimes_sqlids (sql_id) values ('ax6zwhwv70kcs')
	into ca.elapsedtimes_sqlids (sql_id) values ('6fyr83rmcwkd8')
	into ca.elapsedtimes_sqlids (sql_id) values ('4ybrb3k68wnrz')
	into ca.elapsedtimes_sqlids (sql_id) values ('5xdzwas0t0nzt')
	into ca.elapsedtimes_sqlids (sql_id) values ('9hj3cjz5swpf1')
	into ca.elapsedtimes_sqlids (sql_id) values ('3r0qy7bnvcps1')
	into ca.elapsedtimes_sqlids (sql_id) values ('90m13v3jznq79')
	into ca.elapsedtimes_sqlids (sql_id) values ('9yudkdcdu4wms')
	into ca.elapsedtimes_sqlids (sql_id) values ('0fd0kj9asnxtv')
	into ca.elapsedtimes_sqlids (sql_id) values ('68sztu4uxhz12')
	into ca.elapsedtimes_sqlids (sql_id) values ('4tdbcctch4zgs')
	into ca.elapsedtimes_sqlids (sql_id) values ('gf5mw86c35042')
	into ca.elapsedtimes_sqlids (sql_id) values ('5zwchgyn0p05c')
	into ca.elapsedtimes_sqlids (sql_id) values ('gnrtc756kd0ug')
	into ca.elapsedtimes_sqlids (sql_id) values ('0kxrh1961p0z1')
	into ca.elapsedtimes_sqlids (sql_id) values ('2wh06wvxgp1n7')
	into ca.elapsedtimes_sqlids (sql_id) values ('4ndk83kk0j1pg')
	into ca.elapsedtimes_sqlids (sql_id) values ('5nnm935x4d1ud')
	into ca.elapsedtimes_sqlids (sql_id) values ('57abv4bhgx2h2')
	into ca.elapsedtimes_sqlids (sql_id) values ('2n157u5q5x2qk')
	into ca.elapsedtimes_sqlids (sql_id) values ('gqspzdjhat43k')
	into ca.elapsedtimes_sqlids (sql_id) values ('d8g4qbk7vt44t')
	into ca.elapsedtimes_sqlids (sql_id) values ('6b6rwcj21t483')
	into ca.elapsedtimes_sqlids (sql_id) values ('7c9amztks1536')
	into ca.elapsedtimes_sqlids (sql_id) values ('3zfbth85n95mm')
	into ca.elapsedtimes_sqlids (sql_id) values ('gva3bxvsdt662')
	into ca.elapsedtimes_sqlids (sql_id) values ('21b0ggytw17za')
	into ca.elapsedtimes_sqlids (sql_id) values ('a7npnq74g97zk')
	into ca.elapsedtimes_sqlids (sql_id) values ('7m58caka3t89v')
	into ca.elapsedtimes_sqlids (sql_id) values ('8t24u7t2u18c4')
	into ca.elapsedtimes_sqlids (sql_id) values ('60vruu5r5pac8')
	into ca.elapsedtimes_sqlids (sql_id) values ('5cf2vv1f9dazz')
	into ca.elapsedtimes_sqlids (sql_id) values ('3yxqj6qhudc3x')
	into ca.elapsedtimes_sqlids (sql_id) values ('az2dwfjkdjfk1')
	into ca.elapsedtimes_sqlids (sql_id) values ('44yvd2vhk5fk9')
	into ca.elapsedtimes_sqlids (sql_id) values ('160m6xh805fu9')
	into ca.elapsedtimes_sqlids (sql_id) values ('54s90f853jg62')
	into ca.elapsedtimes_sqlids (sql_id) values ('18kc50vug1k5z')
	into ca.elapsedtimes_sqlids (sql_id) values ('2724tunpg1kdc')
	into ca.elapsedtimes_sqlids (sql_id) values ('04phm8zt8tm9n')
	into ca.elapsedtimes_sqlids (sql_id) values ('96cfjn3dcxmk0')
	into ca.elapsedtimes_sqlids (sql_id) values ('f551wjuukxmum')
	into ca.elapsedtimes_sqlids (sql_id) values ('9cr63u83kdncb')
	into ca.elapsedtimes_sqlids (sql_id) values ('3fc854bxkjnza')
	into ca.elapsedtimes_sqlids (sql_id) values ('0md7fcww21p93')
	into ca.elapsedtimes_sqlids (sql_id) values ('9s8jm30m9ppn0')
	into ca.elapsedtimes_sqlids (sql_id) values ('d844cgz7yxqpt')
	into ca.elapsedtimes_sqlids (sql_id) values ('fgf5rtq2r1qwu')
	into ca.elapsedtimes_sqlids (sql_id) values ('bma41739tds4v')
	into ca.elapsedtimes_sqlids (sql_id) values ('6cr566fkg9scr')
	into ca.elapsedtimes_sqlids (sql_id) values ('53cwg3qsk9spr')
	into ca.elapsedtimes_sqlids (sql_id) values ('a0zabnt15dt4m')
	into ca.elapsedtimes_sqlids (sql_id) values ('dd11cy3kwttnw')
	into ca.elapsedtimes_sqlids (sql_id) values ('cwxuy0mpkjv3d')
	into ca.elapsedtimes_sqlids (sql_id) values ('7ucbrwnahtx56')
	into ca.elapsedtimes_sqlids (sql_id) values ('fzczhm6gcpy42')
	into ca.elapsedtimes_sqlids (sql_id) values ('8t3wuyk955zv8')
	into ca.elapsedtimes_sqlids (sql_id) values ('ga8ghh8kw202c')
	into ca.elapsedtimes_sqlids (sql_id) values ('8u08rnhmdy20r')
	into ca.elapsedtimes_sqlids (sql_id) values ('cdf5jqa39q2uv')
	into ca.elapsedtimes_sqlids (sql_id) values ('95a06r8m3y3b9')
	into ca.elapsedtimes_sqlids (sql_id) values ('dkfq81x1xf450')
	into ca.elapsedtimes_sqlids (sql_id) values ('99khnf8p164kt')
	into ca.elapsedtimes_sqlids (sql_id) values ('fhnj7bm51a4sw')
	into ca.elapsedtimes_sqlids (sql_id) values ('ajb81wwmfa6b3')
	into ca.elapsedtimes_sqlids (sql_id) values ('a6gx1cp0jy822')
	into ca.elapsedtimes_sqlids (sql_id) values ('bzc95s6un687d')
	into ca.elapsedtimes_sqlids (sql_id) values ('39j98ccpk28mx')
	into ca.elapsedtimes_sqlids (sql_id) values ('7uvfk3bbnaam4')
	into ca.elapsedtimes_sqlids (sql_id) values ('8ub3f339k2and')
	into ca.elapsedtimes_sqlids (sql_id) values ('bw97mhmfmuapm')
	into ca.elapsedtimes_sqlids (sql_id) values ('470n99n05aavb')
	into ca.elapsedtimes_sqlids (sql_id) values ('661hsdnf96ayv')
	into ca.elapsedtimes_sqlids (sql_id) values ('bh941shdz2b8g')
	into ca.elapsedtimes_sqlids (sql_id) values ('a2rvr65wxybnk')
	into ca.elapsedtimes_sqlids (sql_id) values ('1rt63uzqsfc7c')
	into ca.elapsedtimes_sqlids (sql_id) values ('1zg1awy16qc8y')
	into ca.elapsedtimes_sqlids (sql_id) values ('a5w714xadycs9')
	into ca.elapsedtimes_sqlids (sql_id) values ('53hgfy3mtqcut')
	into ca.elapsedtimes_sqlids (sql_id) values ('8tj2ff6wwaczp')
	into ca.elapsedtimes_sqlids (sql_id) values ('atm00b35xyd34')
	into ca.elapsedtimes_sqlids (sql_id) values ('9dpqxqmf7ud4s')
	into ca.elapsedtimes_sqlids (sql_id) values ('4tnquwgk3yd5v')
	into ca.elapsedtimes_sqlids (sql_id) values ('6v0vzndtg6dtc')
	into ca.elapsedtimes_sqlids (sql_id) values ('3mwgcjywcfdvj')
	into ca.elapsedtimes_sqlids (sql_id) values ('70w72p3rbaf5d')
	into ca.elapsedtimes_sqlids (sql_id) values ('5g8fz9gycufcg')
	into ca.elapsedtimes_sqlids (sql_id) values ('12kgt7aszafgt')
	into ca.elapsedtimes_sqlids (sql_id) values ('gvd6zk77dafvk')
	into ca.elapsedtimes_sqlids (sql_id) values ('72wnfdmv8ujsa')
	into ca.elapsedtimes_sqlids (sql_id) values ('3aa8skczpukf3')
	into ca.elapsedtimes_sqlids (sql_id) values ('1zsbn0u93am2f')
	into ca.elapsedtimes_sqlids (sql_id) values ('30f1vqu7jknac')
	into ca.elapsedtimes_sqlids (sql_id) values ('6sd31qxm2qnq5')
	into ca.elapsedtimes_sqlids (sql_id) values ('cwf357fjn2nu9')
	into ca.elapsedtimes_sqlids (sql_id) values ('aw5gatsdq2pz4')
	into ca.elapsedtimes_sqlids (sql_id) values ('aby832b02fq5q')
	into ca.elapsedtimes_sqlids (sql_id) values ('ds8hy7ywqqrb3')
	into ca.elapsedtimes_sqlids (sql_id) values ('7cta8haxtks0y')
	into ca.elapsedtimes_sqlids (sql_id) values ('fnvqah7rm2s18')
	into ca.elapsedtimes_sqlids (sql_id) values ('8554wt5zmfshq')
	into ca.elapsedtimes_sqlids (sql_id) values ('92bfz2pm4fsps')
	into ca.elapsedtimes_sqlids (sql_id) values ('f67jqx6jqyt38')
	into ca.elapsedtimes_sqlids (sql_id) values ('3c94d3936at9w')
	into ca.elapsedtimes_sqlids (sql_id) values ('g75d27hxg6u7p')
	into ca.elapsedtimes_sqlids (sql_id) values ('6rmbb3s2paun6')
	into ca.elapsedtimes_sqlids (sql_id) values ('0nq91apnd6v6h')
	into ca.elapsedtimes_sqlids (sql_id) values ('bmbcyb7thkwcg')
	into ca.elapsedtimes_sqlids (sql_id) values ('djrzu7tphkwfg')
	into ca.elapsedtimes_sqlids (sql_id) values ('gah42dzukux07')
	into ca.elapsedtimes_sqlids (sql_id) values ('buh9456kkuydq')
	into ca.elapsedtimes_sqlids (sql_id) values ('g3mptxcatkzs9')
	into ca.elapsedtimes_sqlids (sql_id) values ('0ba6bkfb7b01g')
	into ca.elapsedtimes_sqlids (sql_id) values ('7jxjxby66r1gv')
	into ca.elapsedtimes_sqlids (sql_id) values ('btqrjfqsjb1k5')
	into ca.elapsedtimes_sqlids (sql_id) values ('d9x3sxs4b72kz')
	into ca.elapsedtimes_sqlids (sql_id) values ('8pk59yn6773uw')
	into ca.elapsedtimes_sqlids (sql_id) values ('da1satvtsr3vy')
	into ca.elapsedtimes_sqlids (sql_id) values ('7cz7865cj74y3')
	into ca.elapsedtimes_sqlids (sql_id) values ('39vzm1k05z4y4')
	into ca.elapsedtimes_sqlids (sql_id) values ('2s1ydc0f7b5jf')
	into ca.elapsedtimes_sqlids (sql_id) values ('8m3ajaaa6g6q6')
	into ca.elapsedtimes_sqlids (sql_id) values ('83uy96ybcr6xm')
	into ca.elapsedtimes_sqlids (sql_id) values ('apg8426mrrcyx')
	into ca.elapsedtimes_sqlids (sql_id) values ('2cxb37m2tbf1g')
	into ca.elapsedtimes_sqlids (sql_id) values ('93t6vmnct7f56')
	into ca.elapsedtimes_sqlids (sql_id) values ('40kv80xyurfa7')
	into ca.elapsedtimes_sqlids (sql_id) values ('7rwwcmnn47j7n')
	into ca.elapsedtimes_sqlids (sql_id) values ('3gf7bxdhx7k8j')
	into ca.elapsedtimes_sqlids (sql_id) values ('4v5q28wa5bktu')
	into ca.elapsedtimes_sqlids (sql_id) values ('av5sxfmcarmjd')
	into ca.elapsedtimes_sqlids (sql_id) values ('g4uj98336rmp5')
	into ca.elapsedtimes_sqlids (sql_id) values ('9r10sg2n8gms2')
	into ca.elapsedtimes_sqlids (sql_id) values ('25810k9fg7mym')
	into ca.elapsedtimes_sqlids (sql_id) values ('013du64ncgng5')
	into ca.elapsedtimes_sqlids (sql_id) values ('7m3rxm4g4mntv')
	into ca.elapsedtimes_sqlids (sql_id) values ('54fqtfpud7pm4')
	into ca.elapsedtimes_sqlids (sql_id) values ('0q1z406x27psk')
	into ca.elapsedtimes_sqlids (sql_id) values ('fhwkd4d74bqxa')
	into ca.elapsedtimes_sqlids (sql_id) values ('6uwhp3asjvta8')
	into ca.elapsedtimes_sqlids (sql_id) values ('54gxt0tf3ru24')
	into ca.elapsedtimes_sqlids (sql_id) values ('8wzw57469guhb')
	into ca.elapsedtimes_sqlids (sql_id) values ('8fsachrs3gvuz')
	into ca.elapsedtimes_sqlids (sql_id) values ('57u4ahsyu7x02')
	into ca.elapsedtimes_sqlids (sql_id) values ('4juqhs7pzbywf')
	into ca.elapsedtimes_sqlids (sql_id) values ('dg8j3jtyh8236')
	into ca.elapsedtimes_sqlids (sql_id) values ('d9zc3cgdu024r')
	into ca.elapsedtimes_sqlids (sql_id) values ('4xavr8rhmh4rx')
	into ca.elapsedtimes_sqlids (sql_id) values ('gu1xhz698c552')
	into ca.elapsedtimes_sqlids (sql_id) values ('8pa4c66mb85vj')
	into ca.elapsedtimes_sqlids (sql_id) values ('2bcg48rk8h6nf')
	into ca.elapsedtimes_sqlids (sql_id) values ('7su0ayncr07y4')
	into ca.elapsedtimes_sqlids (sql_id) values ('2nps088h908qp')
	into ca.elapsedtimes_sqlids (sql_id) values ('0dsdttcybs9zf')
	into ca.elapsedtimes_sqlids (sql_id) values ('fgtf7gpd0wbc0')
	into ca.elapsedtimes_sqlids (sql_id) values ('48t817tm5nf32')
	into ca.elapsedtimes_sqlids (sql_id) values ('5yckj3135nfvg')
	into ca.elapsedtimes_sqlids (sql_id) values ('7t9z306qfhgty')
	into ca.elapsedtimes_sqlids (sql_id) values ('durvzahsush6u')
	into ca.elapsedtimes_sqlids (sql_id) values ('3jayy670tch8n')
	into ca.elapsedtimes_sqlids (sql_id) values ('gyvdjb2zqnhbj')
	into ca.elapsedtimes_sqlids (sql_id) values ('8753kt4rd8hh9')
	into ca.elapsedtimes_sqlids (sql_id) values ('fsfwuzk8bshun')
	into ca.elapsedtimes_sqlids (sql_id) values ('4buh3jn3m0j2u')
	into ca.elapsedtimes_sqlids (sql_id) values ('cqwtckf4vhjb7')
	into ca.elapsedtimes_sqlids (sql_id) values ('16g5g4p9pwjc7')
	into ca.elapsedtimes_sqlids (sql_id) values ('cq6wdw5yaskd6')
	into ca.elapsedtimes_sqlids (sql_id) values ('2zkwq2jdb8nkk')
	into ca.elapsedtimes_sqlids (sql_id) values ('32zc5hamunpvd')
	into ca.elapsedtimes_sqlids (sql_id) values ('81dsygcc3wr30')
	into ca.elapsedtimes_sqlids (sql_id) values ('grm1m5wac8rpp')
	into ca.elapsedtimes_sqlids (sql_id) values ('fm4y0cd1wnruf')
	into ca.elapsedtimes_sqlids (sql_id) values ('8gxmrff4qhtvv')
	into ca.elapsedtimes_sqlids (sql_id) values ('f704g7fus0vfc')
	into ca.elapsedtimes_sqlids (sql_id) values ('0n6p9221nnvvy')
	into ca.elapsedtimes_sqlids (sql_id) values ('1t396v0j1nw3a')
	into ca.elapsedtimes_sqlids (sql_id) values ('54hbr891hhw7v')
	into ca.elapsedtimes_sqlids (sql_id) values ('4wx4sx7vf8waz')
	into ca.elapsedtimes_sqlids (sql_id) values ('4771fpw5n4xsn')
	into ca.elapsedtimes_sqlids (sql_id) values ('7b378t2v0sy7a')
	into ca.elapsedtimes_sqlids (sql_id) values ('1vf2m7d1dcz1a')
	into ca.elapsedtimes_sqlids (sql_id) values ('3wtbwv4k4508w')
	into ca.elapsedtimes_sqlids (sql_id) values ('8f4qh8zsd50h6')
	into ca.elapsedtimes_sqlids (sql_id) values ('cd72u35h0x0xf')
	into ca.elapsedtimes_sqlids (sql_id) values ('bzgj3wbvp90yj')
	into ca.elapsedtimes_sqlids (sql_id) values ('8ghj1m13bj11w')
	into ca.elapsedtimes_sqlids (sql_id) values ('a1uwb2y4m51za')
	into ca.elapsedtimes_sqlids (sql_id) values ('6g2n6v8dvd2sk')
	into ca.elapsedtimes_sqlids (sql_id) values ('g5m29v9qr53z2')
	into ca.elapsedtimes_sqlids (sql_id) values ('37xhdj22ax43x')
	into ca.elapsedtimes_sqlids (sql_id) values ('730s711kkx4u2')
	into ca.elapsedtimes_sqlids (sql_id) values ('30g3nrfasj56x')
	into ca.elapsedtimes_sqlids (sql_id) values ('9z601brcqp58k')
	into ca.elapsedtimes_sqlids (sql_id) values ('g4s3afr1sd65n')
	into ca.elapsedtimes_sqlids (sql_id) values ('8m3ubzyn1x6jv')
	into ca.elapsedtimes_sqlids (sql_id) values ('g0buwdgj5t7zt')
	into ca.elapsedtimes_sqlids (sql_id) values ('7gb5s84zs1813')
	into ca.elapsedtimes_sqlids (sql_id) values ('cc5fxrgz719f9')
	into ca.elapsedtimes_sqlids (sql_id) values ('6tj9tfj44pa5w')
	into ca.elapsedtimes_sqlids (sql_id) values ('7k69wd2jytbdm')
	into ca.elapsedtimes_sqlids (sql_id) values ('5310nmmq99cp1')
	into ca.elapsedtimes_sqlids (sql_id) values ('ayc01u4x8dctm')
	into ca.elapsedtimes_sqlids (sql_id) values ('cxwn4gb82tfmh')
	into ca.elapsedtimes_sqlids (sql_id) values ('g9tpd6rc25fxu')
	into ca.elapsedtimes_sqlids (sql_id) values ('8z6n6z8q6pg1v')
	into ca.elapsedtimes_sqlids (sql_id) values ('7vy14qs2djg55')
	into ca.elapsedtimes_sqlids (sql_id) values ('6gnr3p42t5gsu')
	into ca.elapsedtimes_sqlids (sql_id) values ('5cgbf7a85xh61')
	into ca.elapsedtimes_sqlids (sql_id) values ('crkm8x5fatjhy')
	into ca.elapsedtimes_sqlids (sql_id) values ('7bhnz935tdjpg')
	into ca.elapsedtimes_sqlids (sql_id) values ('9qm6ts47mdkbn')
	into ca.elapsedtimes_sqlids (sql_id) values ('ccw6tzdjc9kyu')
	into ca.elapsedtimes_sqlids (sql_id) values ('8x8u0yf2rjmcw')
	into ca.elapsedtimes_sqlids (sql_id) values ('4m39uhh8ftmhd')
	into ca.elapsedtimes_sqlids (sql_id) values ('1ufxk4zb09nz8')
	into ca.elapsedtimes_sqlids (sql_id) values ('dxuhdzkzwtqad')
	into ca.elapsedtimes_sqlids (sql_id) values ('bcrhkxk3bxqwb')
	into ca.elapsedtimes_sqlids (sql_id) values ('1v07zt4ym1skz')
	into ca.elapsedtimes_sqlids (sql_id) values ('cat0mr6q9xssy')
	into ca.elapsedtimes_sqlids (sql_id) values ('f7yqntyfh9t2u')
	into ca.elapsedtimes_sqlids (sql_id) values ('52unp4u4gxu44')
	into ca.elapsedtimes_sqlids (sql_id) values ('40zj2quf1xwfv')
	into ca.elapsedtimes_sqlids (sql_id) values ('0yk24wxsujy91')
	into ca.elapsedtimes_sqlids (sql_id) values ('b2tdxqduf1yh8')
	into ca.elapsedtimes_sqlids (sql_id) values ('8zumzv2n1pz4c')
	into ca.elapsedtimes_sqlids (sql_id) values ('3mrajd57by066')
	into ca.elapsedtimes_sqlids (sql_id) values ('2amzzr8bj60c9')
	into ca.elapsedtimes_sqlids (sql_id) values ('6m8mscp8zy1bd')
	into ca.elapsedtimes_sqlids (sql_id) values ('gcdnwpfb5k1tc')
	into ca.elapsedtimes_sqlids (sql_id) values ('gqw9vc51uq1vp')
	into ca.elapsedtimes_sqlids (sql_id) values ('8ravgadg2y1ym')
	into ca.elapsedtimes_sqlids (sql_id) values ('0b93bcbuqk29n')
	into ca.elapsedtimes_sqlids (sql_id) values ('dwa462gn922gy')
	into ca.elapsedtimes_sqlids (sql_id) values ('82tjnkyhka2n5')
	into ca.elapsedtimes_sqlids (sql_id) values ('286uq2xamk2uy')
	into ca.elapsedtimes_sqlids (sql_id) values ('6jsn9627v22wk')
	into ca.elapsedtimes_sqlids (sql_id) values ('guzywxfyvf4kp')
	into ca.elapsedtimes_sqlids (sql_id) values ('gzbc3wx82f4u9')
	into ca.elapsedtimes_sqlids (sql_id) values ('0zhmr9d7ya6mz')
	into ca.elapsedtimes_sqlids (sql_id) values ('6nv0d77g8f8rr')
	into ca.elapsedtimes_sqlids (sql_id) values ('avaf7f31bk980')
	into ca.elapsedtimes_sqlids (sql_id) values ('8d70fhqusybxk')
	into ca.elapsedtimes_sqlids (sql_id) values ('4dtw88fvwud9u')
	into ca.elapsedtimes_sqlids (sql_id) values ('akh90k31vkd9u')
	into ca.elapsedtimes_sqlids (sql_id) values ('23ag7krh8fda3')
	into ca.elapsedtimes_sqlids (sql_id) values ('5rzswurfa2dfw')
	into ca.elapsedtimes_sqlids (sql_id) values ('4fym5vw8v2dth')
	into ca.elapsedtimes_sqlids (sql_id) values ('c6ubvn6582f2w')
	into ca.elapsedtimes_sqlids (sql_id) values ('gzs2r53x12fzx')
	into ca.elapsedtimes_sqlids (sql_id) values ('an4kgdskyfhc2')
	into ca.elapsedtimes_sqlids (sql_id) values ('adscqgp91yjkp')
	into ca.elapsedtimes_sqlids (sql_id) values ('dws6nhx7tqkc2')
	into ca.elapsedtimes_sqlids (sql_id) values ('3gkmks4sk6km0')
	into ca.elapsedtimes_sqlids (sql_id) values ('ghtdvxth4qmug')
	into ca.elapsedtimes_sqlids (sql_id) values ('1ku7hkr5u2nfq')
	into ca.elapsedtimes_sqlids (sql_id) values ('5611gu1p22p35')
	into ca.elapsedtimes_sqlids (sql_id) values ('4f0h43swwup9f')
	into ca.elapsedtimes_sqlids (sql_id) values ('7yf1v0bhw6pdw')
	into ca.elapsedtimes_sqlids (sql_id) values ('d90muqukqkpgx')
	into ca.elapsedtimes_sqlids (sql_id) values ('5qy1dfs8sfrg9')
	into ca.elapsedtimes_sqlids (sql_id) values ('fjrc0bggdut6z')
	into ca.elapsedtimes_sqlids (sql_id) values ('cwjs82vqhyt78')
	into ca.elapsedtimes_sqlids (sql_id) values ('a66x3yx2g6tx7')
	into ca.elapsedtimes_sqlids (sql_id) values ('f7470zbr8uv5t')
	into ca.elapsedtimes_sqlids (sql_id) values ('cxf0kx1v22v6m')
	into ca.elapsedtimes_sqlids (sql_id) values ('4tv3qrfm0kv75')
	into ca.elapsedtimes_sqlids (sql_id) values ('d80vvrwuuuw51')
	into ca.elapsedtimes_sqlids (sql_id) values ('977xkvqagywts')
	into ca.elapsedtimes_sqlids (sql_id) values ('8d66k773rqxfu')
	into ca.elapsedtimes_sqlids (sql_id) values ('153j74294yxtv')
	into ca.elapsedtimes_sqlids (sql_id) values ('b3zt66vf7v0tc')
	into ca.elapsedtimes_sqlids (sql_id) values ('g59va1pfpv2xk')
	into ca.elapsedtimes_sqlids (sql_id) values ('41djhga3u7536')
	into ca.elapsedtimes_sqlids (sql_id) values ('dtrwm6r02g57u')
	into ca.elapsedtimes_sqlids (sql_id) values ('bxsfhpvvhv5t5')
	into ca.elapsedtimes_sqlids (sql_id) values ('dbvdn3bcxg5w1')
	into ca.elapsedtimes_sqlids (sql_id) values ('c6wvgzx1r76fr')
	into ca.elapsedtimes_sqlids (sql_id) values ('9bxgh9g6um747')
	into ca.elapsedtimes_sqlids (sql_id) values ('a7tk7472bz788')
	into ca.elapsedtimes_sqlids (sql_id) values ('34m08spf1g7mv')
	into ca.elapsedtimes_sqlids (sql_id) values ('b23ajz17qv8t1')
	into ca.elapsedtimes_sqlids (sql_id) values ('94tv7w5gq39mv')
	into ca.elapsedtimes_sqlids (sql_id) values ('7w3us978wg9xv')
	into ca.elapsedtimes_sqlids (sql_id) values ('9c69r25rhzcwz')
	into ca.elapsedtimes_sqlids (sql_id) values ('6s9u4kzxxgd2g')
	into ca.elapsedtimes_sqlids (sql_id) values ('gh4dmmzcd3dfm')
	into ca.elapsedtimes_sqlids (sql_id) values ('0tk5rymwcvg8w')
	into ca.elapsedtimes_sqlids (sql_id) values ('d878rcxddvgh7')
	into ca.elapsedtimes_sqlids (sql_id) values ('gxyv5317r7gsk')
	into ca.elapsedtimes_sqlids (sql_id) values ('2ydfwr60mgguy')
	into ca.elapsedtimes_sqlids (sql_id) values ('b2fxxuq8hgjsu')
	into ca.elapsedtimes_sqlids (sql_id) values ('7ag1utw2agmb7')
	into ca.elapsedtimes_sqlids (sql_id) values ('2q62nqnamzmj5')
	into ca.elapsedtimes_sqlids (sql_id) values ('3dkwyah5hvnf4')
	into ca.elapsedtimes_sqlids (sql_id) values ('116kn2mwk7p7m')
	into ca.elapsedtimes_sqlids (sql_id) values ('7pvadpnkp3ppb')
	into ca.elapsedtimes_sqlids (sql_id) values ('2f7r6yvchmppf')
	into ca.elapsedtimes_sqlids (sql_id) values ('69aj21fsfbpq3')
	into ca.elapsedtimes_sqlids (sql_id) values ('cnk4ur67pbpwh')
	into ca.elapsedtimes_sqlids (sql_id) values ('dfjqz1zm5rqxc')
	into ca.elapsedtimes_sqlids (sql_id) values ('8msg6cgd9brjv')
	into ca.elapsedtimes_sqlids (sql_id) values ('51bw9zsjcgsga')
	into ca.elapsedtimes_sqlids (sql_id) values ('0td4wsbkqgsws')
	into ca.elapsedtimes_sqlids (sql_id) values ('b8jbbcsqr7tgg')
	into ca.elapsedtimes_sqlids (sql_id) values ('7gngn8mb6ztwm')
	into ca.elapsedtimes_sqlids (sql_id) values ('az1yk9rdn7txt')
	into ca.elapsedtimes_sqlids (sql_id) values ('3fk0h6dbtmvjb')
	into ca.elapsedtimes_sqlids (sql_id) values ('8dn9rsmv8gw57')
	into ca.elapsedtimes_sqlids (sql_id) values ('cp0d3daqtbwz7')
	into ca.elapsedtimes_sqlids (sql_id) values ('a6t32j7sumy0q')
	into ca.elapsedtimes_sqlids (sql_id) values ('57ckxfh6yzy5d')
	into ca.elapsedtimes_sqlids (sql_id) values ('6k3zwpf4rgyw3')
	into ca.elapsedtimes_sqlids (sql_id) values ('61w5wjkx7mzb8')
	into ca.elapsedtimes_sqlids (sql_id) values ('az1d9yuskrznp')
	into ca.elapsedtimes_sqlids (sql_id) values ('320c5cghdh0nk')
	into ca.elapsedtimes_sqlids (sql_id) values ('4f0cj23c0n1n2')
	into ca.elapsedtimes_sqlids (sql_id) values ('7srqc7k4u829d')
	into ca.elapsedtimes_sqlids (sql_id) values ('a66a8rxc542d1')
	into ca.elapsedtimes_sqlids (sql_id) values ('2gzgw62tuw2za')
	into ca.elapsedtimes_sqlids (sql_id) values ('5d6pgzkn7w3wh')
	into ca.elapsedtimes_sqlids (sql_id) values ('8ycwzdhg984wr')
	into ca.elapsedtimes_sqlids (sql_id) values ('95hz6bwd045kk')
	into ca.elapsedtimes_sqlids (sql_id) values ('05rh855dks6pc')
	into ca.elapsedtimes_sqlids (sql_id) values ('ady5ztq3nw753')
	into ca.elapsedtimes_sqlids (sql_id) values ('f5u6zu50rn772')
	into ca.elapsedtimes_sqlids (sql_id) values ('469z1j73587b5')
	into ca.elapsedtimes_sqlids (sql_id) values ('8bj2y8tm5cap7')
	into ca.elapsedtimes_sqlids (sql_id) values ('0cbsz43ukcasm')
	into ca.elapsedtimes_sqlids (sql_id) values ('0k33uf02n4f6c')
	into ca.elapsedtimes_sqlids (sql_id) values ('4dkc1t422hgph')
	into ca.elapsedtimes_sqlids (sql_id) values ('bsmnr0tcuhgq1')
	into ca.elapsedtimes_sqlids (sql_id) values ('82gg312na8j3j')
	into ca.elapsedtimes_sqlids (sql_id) values ('g90haxu2shjgp')
	into ca.elapsedtimes_sqlids (sql_id) values ('gyrtsn2f0cjnj')
	into ca.elapsedtimes_sqlids (sql_id) values ('1r26c1jthnkpb')
	into ca.elapsedtimes_sqlids (sql_id) values ('3p0mvr3c0hkyb')
	into ca.elapsedtimes_sqlids (sql_id) values ('g50q3tk1uhn8z')
	into ca.elapsedtimes_sqlids (sql_id) values ('fujwhud0r4qqx')
	into ca.elapsedtimes_sqlids (sql_id) values ('166gsh1d6cthf')
	into ca.elapsedtimes_sqlids (sql_id) values ('7jcxmph1z8tzd')
	into ca.elapsedtimes_sqlids (sql_id) values ('6nz3zsnya0ubk')
	into ca.elapsedtimes_sqlids (sql_id) values ('6azmqtf5b4v94')
	into ca.elapsedtimes_sqlids (sql_id) values ('657nq2cbwnv9s')
	into ca.elapsedtimes_sqlids (sql_id) values ('8nzhacygy0wcf')
	into ca.elapsedtimes_sqlids (sql_id) values ('b8x3b1wgk8ytr')
	into ca.elapsedtimes_sqlids (sql_id) values ('3bkmbvk8tsz99')
	into ca.elapsedtimes_sqlids (sql_id) values ('dzp8874b5nzmz')
	into ca.elapsedtimes_sqlids (sql_id) values ('2marxaf2m90hb')
	into ca.elapsedtimes_sqlids (sql_id) values ('8cpxbkuzjp16x')
	into ca.elapsedtimes_sqlids (sql_id) values ('cxfk67x66x232')
	into ca.elapsedtimes_sqlids (sql_id) values ('648s1h1vw12ap')
	into ca.elapsedtimes_sqlids (sql_id) values ('cmdrjxc8212mw')
	into ca.elapsedtimes_sqlids (sql_id) values ('1znjwwtbtd2sg')
	into ca.elapsedtimes_sqlids (sql_id) values ('7wnqt6w0fd2uj')
	into ca.elapsedtimes_sqlids (sql_id) values ('59u7uubdyp3bf')
	into ca.elapsedtimes_sqlids (sql_id) values ('fndvm3gqm93uu')
	into ca.elapsedtimes_sqlids (sql_id) values ('f8zv6d7n513w0')
	into ca.elapsedtimes_sqlids (sql_id) values ('cd5dy8zj893wq')
	into ca.elapsedtimes_sqlids (sql_id) values ('6a4dfc4nfj4z4')
	into ca.elapsedtimes_sqlids (sql_id) values ('5ajzus7f8556c')
	into ca.elapsedtimes_sqlids (sql_id) values ('gj5a0h3yb56cg')
	into ca.elapsedtimes_sqlids (sql_id) values ('6sh5h66hrx6jj')
	into ca.elapsedtimes_sqlids (sql_id) values ('8cdrfruxdx8wk')
	into ca.elapsedtimes_sqlids (sql_id) values ('a1r6hkmcw58yh')
	into ca.elapsedtimes_sqlids (sql_id) values ('cyjd1d4d7tbw1')
	into ca.elapsedtimes_sqlids (sql_id) values ('g3ukmtcugxdpt')
	into ca.elapsedtimes_sqlids (sql_id) values ('fmm18t3c7dfmd')
	into ca.elapsedtimes_sqlids (sql_id) values ('gtj8ab51u9gsn')
	into ca.elapsedtimes_sqlids (sql_id) values ('9sw963zmupgtv')
	into ca.elapsedtimes_sqlids (sql_id) values ('0xwg8uw67jhc8')
	into ca.elapsedtimes_sqlids (sql_id) values ('c1xfabg779hn9')
	into ca.elapsedtimes_sqlids (sql_id) values ('4tar254xy5j4p')
	into ca.elapsedtimes_sqlids (sql_id) values ('dkqt0qczcpkrz')
	into ca.elapsedtimes_sqlids (sql_id) values ('8gjzhd9wmxkvd')
	into ca.elapsedtimes_sqlids (sql_id) values ('dyp9zfcyz5n3p')
	into ca.elapsedtimes_sqlids (sql_id) values ('85zht1qtrxnhg')
	into ca.elapsedtimes_sqlids (sql_id) values ('a46qtqbx9tqb2')
	into ca.elapsedtimes_sqlids (sql_id) values ('3c29mmxnf9rg5')
	into ca.elapsedtimes_sqlids (sql_id) values ('c2g9yyfcfttay')
	into ca.elapsedtimes_sqlids (sql_id) values ('f5g91x9695u80')
	into ca.elapsedtimes_sqlids (sql_id) values ('228cy4s245ucw')
	into ca.elapsedtimes_sqlids (sql_id) values ('b9czjr0aftv2t')
	into ca.elapsedtimes_sqlids (sql_id) values ('530cg550jpvbw')
	into ca.elapsedtimes_sqlids (sql_id) values ('bm4p4kqdzjvxq')
	into ca.elapsedtimes_sqlids (sql_id) values ('9gcdyarscxw2p')
	into ca.elapsedtimes_sqlids (sql_id) values ('5z1kyf0ghpx6u')
	into ca.elapsedtimes_sqlids (sql_id) values ('3fadgkhbndxd5')
	into ca.elapsedtimes_sqlids (sql_id) values ('dwdtfbcz6jxjf')
	into ca.elapsedtimes_sqlids (sql_id) values ('gdxnxz20n5xwa')
	into ca.elapsedtimes_sqlids (sql_id) values ('0vr6mjtw3xybz')
	into ca.elapsedtimes_sqlids (sql_id) values ('fszbxtjrzdz7x')
	into ca.elapsedtimes_sqlids (sql_id) values ('4ztyuffsbpzas')
	into ca.elapsedtimes_sqlids (sql_id) values ('gbhg0wx322048')
	into ca.elapsedtimes_sqlids (sql_id) values ('99mtsmanxa1ub')
	into ca.elapsedtimes_sqlids (sql_id) values ('crrhjtxm4f48x')
	into ca.elapsedtimes_sqlids (sql_id) values ('55krqjs07a4bf')
	into ca.elapsedtimes_sqlids (sql_id) values ('2cf4zk5ddk59v')
	into ca.elapsedtimes_sqlids (sql_id) values ('39d3jp19af5cp')
	into ca.elapsedtimes_sqlids (sql_id) values ('c6n9na98ja5vn')
	into ca.elapsedtimes_sqlids (sql_id) values ('c9abfhh9ha6fa')
	into ca.elapsedtimes_sqlids (sql_id) values ('5jkauugfyq7na')
	into ca.elapsedtimes_sqlids (sql_id) values ('1ygd69ujmu80r')
	into ca.elapsedtimes_sqlids (sql_id) values ('5gjnxsc38a8qw')
	into ca.elapsedtimes_sqlids (sql_id) values ('3p3m64pp1f8vq')
	into ca.elapsedtimes_sqlids (sql_id) values ('7p281gszk69bs')
	into ca.elapsedtimes_sqlids (sql_id) values ('annwmf0cckarr')
	into ca.elapsedtimes_sqlids (sql_id) values ('3dvxcyr336btf')
	into ca.elapsedtimes_sqlids (sql_id) values ('gnknxw5xu6c2s')
	into ca.elapsedtimes_sqlids (sql_id) values ('bqvw6x39f2cgk')
	into ca.elapsedtimes_sqlids (sql_id) values ('f1uszcuq96chc')
	into ca.elapsedtimes_sqlids (sql_id) values ('4j863qt9t6d3x')
	into ca.elapsedtimes_sqlids (sql_id) values ('8s0ayypsgqdmn')
	into ca.elapsedtimes_sqlids (sql_id) values ('43233tmx9kgap')
	into ca.elapsedtimes_sqlids (sql_id) values ('0u53gj9vyqgfy')
	into ca.elapsedtimes_sqlids (sql_id) values ('77mgtjhcykh74')
	into ca.elapsedtimes_sqlids (sql_id) values ('17vdxpfd0ahg0')
	into ca.elapsedtimes_sqlids (sql_id) values ('f68gyb1r22j0k')
	into ca.elapsedtimes_sqlids (sql_id) values ('2f1mpc26x6kcv')
	into ca.elapsedtimes_sqlids (sql_id) values ('fmqv3hq4x6m8f')
	into ca.elapsedtimes_sqlids (sql_id) values ('7xj2ygc09ymda')
	into ca.elapsedtimes_sqlids (sql_id) values ('03qkkghy72ngs')
	into ca.elapsedtimes_sqlids (sql_id) values ('grzv2aw5w6nmn')
	into ca.elapsedtimes_sqlids (sql_id) values ('g7jsab61paq5g')
	into ca.elapsedtimes_sqlids (sql_id) values ('1nf8zgvs96qpm')
	into ca.elapsedtimes_sqlids (sql_id) values ('6umv78qkzyrtm')
	into ca.elapsedtimes_sqlids (sql_id) values ('czc4rms99ktat')
	into ca.elapsedtimes_sqlids (sql_id) values ('3cm35fqghfthw')
	into ca.elapsedtimes_sqlids (sql_id) values ('82sr72cctyty4')
	into ca.elapsedtimes_sqlids (sql_id) values ('brmwxqf8mutyt')
	into ca.elapsedtimes_sqlids (sql_id) values ('22498v1ar2uw8')
	into ca.elapsedtimes_sqlids (sql_id) values ('axxpcb688qvv7')
	into ca.elapsedtimes_sqlids (sql_id) values ('8r82w9svpux9y')
	into ca.elapsedtimes_sqlids (sql_id) values ('at30mu1yqyxcj')
	into ca.elapsedtimes_sqlids (sql_id) values ('954r2sw186y6c')
	into ca.elapsedtimes_sqlids (sql_id) values ('9zn0w4ad6fyu4')
	into ca.elapsedtimes_sqlids (sql_id) values ('3d7rb8kd0uz7s')
	into ca.elapsedtimes_sqlids (sql_id) values ('cnwmzf4r2uzam')
	into ca.elapsedtimes_sqlids (sql_id) values ('4f6g0m7yayzkv')
	into ca.elapsedtimes_sqlids (sql_id) values ('dc5cg7w8fkznf')
	into ca.elapsedtimes_sqlids (sql_id) values ('b9bsvub6jfzsw')
	into ca.elapsedtimes_sqlids (sql_id) values ('5qwrth2mzaztn')
	into ca.elapsedtimes_sqlids (sql_id) values ('9rwr46mj6705v')
	into ca.elapsedtimes_sqlids (sql_id) values ('6dahuxdthr0d4')
	into ca.elapsedtimes_sqlids (sql_id) values ('96b04mwr0716a')
	into ca.elapsedtimes_sqlids (sql_id) values ('0guszbcwnv1sh')
	into ca.elapsedtimes_sqlids (sql_id) values ('6n8v9kjzfb1yz')
	into ca.elapsedtimes_sqlids (sql_id) values ('11s2p5zhmz2jb')
	into ca.elapsedtimes_sqlids (sql_id) values ('0ubv3r1ac32qz')
	into ca.elapsedtimes_sqlids (sql_id) values ('55q6x9n2db33r')
	into ca.elapsedtimes_sqlids (sql_id) values ('3vv1crbps33wg')
	into ca.elapsedtimes_sqlids (sql_id) values ('9kq312bjj74p7')
	into ca.elapsedtimes_sqlids (sql_id) values ('cbxd6s7kvb5d9')
	into ca.elapsedtimes_sqlids (sql_id) values ('895zmfykgr60s')
	into ca.elapsedtimes_sqlids (sql_id) values ('5qb2k79muv67y')
	into ca.elapsedtimes_sqlids (sql_id) values ('3fyn6n36kg7vr')
	into ca.elapsedtimes_sqlids (sql_id) values ('bcgyzk69mz7yw')
	into ca.elapsedtimes_sqlids (sql_id) values ('88arg8q0sb8t6')
	into ca.elapsedtimes_sqlids (sql_id) values ('3wcpagryxm8xj')
	into ca.elapsedtimes_sqlids (sql_id) values ('5guts3du779c2')
	into ca.elapsedtimes_sqlids (sql_id) values ('7hsfb77z7m9r9')
	into ca.elapsedtimes_sqlids (sql_id) values ('3z627gb1a7bfm')
	into ca.elapsedtimes_sqlids (sql_id) values ('bvgb0khh83bh0')
	into ca.elapsedtimes_sqlids (sql_id) values ('0xkvbd5wxvc11')
	into ca.elapsedtimes_sqlids (sql_id) values ('afd5xjhy2mdjg')
	into ca.elapsedtimes_sqlids (sql_id) values ('a5pu899d7bdu7')
	into ca.elapsedtimes_sqlids (sql_id) values ('31rbyh37fbgk6')
	into ca.elapsedtimes_sqlids (sql_id) values ('0npt1zju23j7q')
	into ca.elapsedtimes_sqlids (sql_id) values ('52232m1fsrjgz')
	into ca.elapsedtimes_sqlids (sql_id) values ('6amhnr9thrjxy')
	into ca.elapsedtimes_sqlids (sql_id) values ('fr5fdnmb3rks3')
	into ca.elapsedtimes_sqlids (sql_id) values ('8narqmz44zm1w')
	into ca.elapsedtimes_sqlids (sql_id) values ('frdc06z5kgm2v')
	into ca.elapsedtimes_sqlids (sql_id) values ('fw78p3fd6vq8v')
	into ca.elapsedtimes_sqlids (sql_id) values ('cxhku5pwabr2w')
	into ca.elapsedtimes_sqlids (sql_id) values ('4jv580gzu3r3t')
	into ca.elapsedtimes_sqlids (sql_id) values ('b4xncgbzuvrj5')
	into ca.elapsedtimes_sqlids (sql_id) values ('b3rnt2p0rgrwc')
	into ca.elapsedtimes_sqlids (sql_id) values ('1kdd9pjmnbsbj')
	into ca.elapsedtimes_sqlids (sql_id) values ('7693kb3rqzw9s')
	into ca.elapsedtimes_sqlids (sql_id) values ('fjpkxgrc7ry7k')
	into ca.elapsedtimes_sqlids (sql_id) values ('g2y3hk47ww0z0')
	into ca.elapsedtimes_sqlids (sql_id) values ('02s7c7a4qw1af')
	into ca.elapsedtimes_sqlids (sql_id) values ('a7f7xxupwn1sx')
	into ca.elapsedtimes_sqlids (sql_id) values ('ffd317dyz01un')
	into ca.elapsedtimes_sqlids (sql_id) values ('gbvt8jary42vc')
	into ca.elapsedtimes_sqlids (sql_id) values ('a4z6qwz0sn38f')
	into ca.elapsedtimes_sqlids (sql_id) values ('1b17866mr83kh')
	into ca.elapsedtimes_sqlids (sql_id) values ('da9cawpjqn3mr')
	into ca.elapsedtimes_sqlids (sql_id) values ('5kmxamv67w3n3')
	into ca.elapsedtimes_sqlids (sql_id) values ('bucan5az0s3rt')
	into ca.elapsedtimes_sqlids (sql_id) values ('1rws1u8mc47fj')
	into ca.elapsedtimes_sqlids (sql_id) values ('3y6xy9jkaw8v9')
	into ca.elapsedtimes_sqlids (sql_id) values ('ba8dqr4g989gb')
	into ca.elapsedtimes_sqlids (sql_id) values ('1uxqbxwpmwbp9')
	into ca.elapsedtimes_sqlids (sql_id) values ('a24bk2p844ckk')
	into ca.elapsedtimes_sqlids (sql_id) values ('99grf62200dj6')
	into ca.elapsedtimes_sqlids (sql_id) values ('dsc1yxs15sfun')
	into ca.elapsedtimes_sqlids (sql_id) values ('cnrny8tpthgas')
	into ca.elapsedtimes_sqlids (sql_id) values ('aq189mt11cj7c')
	into ca.elapsedtimes_sqlids (sql_id) values ('ghd9ahwncnjkx')
	into ca.elapsedtimes_sqlids (sql_id) values ('ckkfkxndgsjxh')
	into ca.elapsedtimes_sqlids (sql_id) values ('8rmwukxgusks0')
	into ca.elapsedtimes_sqlids (sql_id) values ('a1q7hun4d4kxh')
	into ca.elapsedtimes_sqlids (sql_id) values ('1vd6qxdwb4n0w')
	into ca.elapsedtimes_sqlids (sql_id) values ('dzhbfh1nc4n13')
	into ca.elapsedtimes_sqlids (sql_id) values ('1zbqxazkvwnd3')
	into ca.elapsedtimes_sqlids (sql_id) values ('5rmajk64y8nzv')
	into ca.elapsedtimes_sqlids (sql_id) values ('0kauab59xhqbz')
	into ca.elapsedtimes_sqlids (sql_id) values ('1shfmwar1crd0')
	into ca.elapsedtimes_sqlids (sql_id) values ('ajtbhf41yhryn')
	into ca.elapsedtimes_sqlids (sql_id) values ('a68ur8vph0ssw')
	into ca.elapsedtimes_sqlids (sql_id) values ('9drbyw7cvnstk')
	into ca.elapsedtimes_sqlids (sql_id) values ('a6q3xtmk4wuvp')
	into ca.elapsedtimes_sqlids (sql_id) values ('36amb92du8v2v')
	into ca.elapsedtimes_sqlids (sql_id) values ('63m80a7rqsvjh')
	into ca.elapsedtimes_sqlids (sql_id) values ('bqvz7vusj0wqb')
	into ca.elapsedtimes_sqlids (sql_id) values ('7fkr9rhnsswwu')
	into ca.elapsedtimes_sqlids (sql_id) values ('8fh1w7hrg0xr2')
	into ca.elapsedtimes_sqlids (sql_id) values ('0ctcfufdvcy62')
	into ca.elapsedtimes_sqlids (sql_id) values ('16jxugr6c0ynq')
	into ca.elapsedtimes_sqlids (sql_id) values ('66j9stgz3hyrk')
	into ca.elapsedtimes_sqlids (sql_id) values ('9cn8nsg4t0z0f')
	into ca.elapsedtimes_sqlids (sql_id) values ('17hmynzgnx161')
	into ca.elapsedtimes_sqlids (sql_id) values ('bgbd5aa5s11r3')
	into ca.elapsedtimes_sqlids (sql_id) values ('b656fg0b7d24y')
	into ca.elapsedtimes_sqlids (sql_id) values ('36fd2j3fc92qs')
	into ca.elapsedtimes_sqlids (sql_id) values ('0zy022q9kt2uz')
	into ca.elapsedtimes_sqlids (sql_id) values ('9mc06b8r312vx')
	into ca.elapsedtimes_sqlids (sql_id) values ('3sym7gq2z9425')
	into ca.elapsedtimes_sqlids (sql_id) values ('dmbvpck5y94wu')
	into ca.elapsedtimes_sqlids (sql_id) values ('027akxha915u6')
	into ca.elapsedtimes_sqlids (sql_id) values ('7arygrm9cp5y3')
	into ca.elapsedtimes_sqlids (sql_id) values ('1u7k59xyct6v1')
	into ca.elapsedtimes_sqlids (sql_id) values ('84ghq9mxu97t5')
	into ca.elapsedtimes_sqlids (sql_id) values ('2tr6hsfgg98px')
	into ca.elapsedtimes_sqlids (sql_id) values ('bh91m31uvt90q')
	into ca.elapsedtimes_sqlids (sql_id) values ('cw9ajnxytta58')
	into ca.elapsedtimes_sqlids (sql_id) values ('a98f2hyw2pbw8')
	into ca.elapsedtimes_sqlids (sql_id) values ('02ug1nr9gjcst')
	into ca.elapsedtimes_sqlids (sql_id) values ('cu8701mcntg4b')
	into ca.elapsedtimes_sqlids (sql_id) values ('26yrpwgquxh06')
	into ca.elapsedtimes_sqlids (sql_id) values ('4fhrn7182thw3')
	into ca.elapsedtimes_sqlids (sql_id) values ('59pyusr2p9hxn')
	into ca.elapsedtimes_sqlids (sql_id) values ('7n1p4y6fz5jc1')
	into ca.elapsedtimes_sqlids (sql_id) values ('6rptd7f5f9k1y')
	into ca.elapsedtimes_sqlids (sql_id) values ('69kptm3ds1k3q')
	into ca.elapsedtimes_sqlids (sql_id) values ('f5turnszg9ku2')
	into ca.elapsedtimes_sqlids (sql_id) values ('9j4wkm5hspkz4')
	into ca.elapsedtimes_sqlids (sql_id) values ('f8pywqksp5mv5')
	into ca.elapsedtimes_sqlids (sql_id) values ('2d3wb83g6xn3p')
	into ca.elapsedtimes_sqlids (sql_id) values ('cg88rjs8ydnzr')
	into ca.elapsedtimes_sqlids (sql_id) values ('avwhu1z22pp01')
	into ca.elapsedtimes_sqlids (sql_id) values ('7ykam51fsxpah')
	into ca.elapsedtimes_sqlids (sql_id) values ('gv2wghw9mtqpx')
	into ca.elapsedtimes_sqlids (sql_id) values ('fcyuwxw8cjrab')
	into ca.elapsedtimes_sqlids (sql_id) values ('atqjfa5nz1rc6')
	into ca.elapsedtimes_sqlids (sql_id) values ('3xdcant76pt87')
	into ca.elapsedtimes_sqlids (sql_id) values ('3nkym55rb9tjs')
	into ca.elapsedtimes_sqlids (sql_id) values ('fww1q2a471ugd')
	into ca.elapsedtimes_sqlids (sql_id) values ('ch3u318rkpwc4')
	into ca.elapsedtimes_sqlids (sql_id) values ('9tgftu07ktwzb')
	into ca.elapsedtimes_sqlids (sql_id) values ('5mvyg0h2ydx31')
	into ca.elapsedtimes_sqlids (sql_id) values ('g3uzt1ph1tx54')
	into ca.elapsedtimes_sqlids (sql_id) values ('bxh00apyzxyr3')
	into ca.elapsedtimes_sqlids (sql_id) values ('gsvry9zx8tz2j')
	into ca.elapsedtimes_sqlids (sql_id) values ('gvjv1dt6ru0d8')
	into ca.elapsedtimes_sqlids (sql_id) values ('8dgswh9j8217c')
	into ca.elapsedtimes_sqlids (sql_id) values ('6vruzvdd9y1wj')
	into ca.elapsedtimes_sqlids (sql_id) values ('25f17n8udu2d5')
	into ca.elapsedtimes_sqlids (sql_id) values ('6t2m46v89a2h6')
	into ca.elapsedtimes_sqlids (sql_id) values ('a840379xyu38g')
	into ca.elapsedtimes_sqlids (sql_id) values ('1agst43d065dv')
	into ca.elapsedtimes_sqlids (sql_id) values ('1fytdr4gmu66m')
	into ca.elapsedtimes_sqlids (sql_id) values ('c46493f8xa69d')
	into ca.elapsedtimes_sqlids (sql_id) values ('b9b7f0phbq6d4')
	into ca.elapsedtimes_sqlids (sql_id) values ('g9stv9gsqaa5n')
	into ca.elapsedtimes_sqlids (sql_id) values ('3kkk7arct6bkd')
	into ca.elapsedtimes_sqlids (sql_id) values ('8jq297fxj6c5r')
	into ca.elapsedtimes_sqlids (sql_id) values ('9ddq4mr422c9s')
	into ca.elapsedtimes_sqlids (sql_id) values ('3rjxp755quczt')
	into ca.elapsedtimes_sqlids (sql_id) values ('5xxspq5vg6d4y')
	into ca.elapsedtimes_sqlids (sql_id) values ('0wd0hjvhaqd7k')
	into ca.elapsedtimes_sqlids (sql_id) values ('2q15g0xp42jph')
	into ca.elapsedtimes_sqlids (sql_id) values ('4y1pq60jhykku')
	into ca.elapsedtimes_sqlids (sql_id) values ('g7nbc0hsx2kt0')
	into ca.elapsedtimes_sqlids (sql_id) values ('2a48rcj2vfnqv')
	into ca.elapsedtimes_sqlids (sql_id) values ('b5jyp9vywfqhc')
	into ca.elapsedtimes_sqlids (sql_id) values ('ck1b54wp72qu8')
	into ca.elapsedtimes_sqlids (sql_id) values ('08uqv5pr2yr1b')
	into ca.elapsedtimes_sqlids (sql_id) values ('1s7rzcbdburas')
	into ca.elapsedtimes_sqlids (sql_id) values ('7bqrb9337usrd')
	into ca.elapsedtimes_sqlids (sql_id) values ('d9w4fhx4rutta')
	into ca.elapsedtimes_sqlids (sql_id) values ('4ddvkm0zd2tug')
	into ca.elapsedtimes_sqlids (sql_id) values ('b9mpkmu61uty2')
	into ca.elapsedtimes_sqlids (sql_id) values ('d66rghb42ktym')
	into ca.elapsedtimes_sqlids (sql_id) values ('gy08c0m5z6u08')
	into ca.elapsedtimes_sqlids (sql_id) values ('50s857katuurn')
	into ca.elapsedtimes_sqlids (sql_id) values ('c66jm9d9auvrf')
	into ca.elapsedtimes_sqlids (sql_id) values ('513utkt9hqy84')
	into ca.elapsedtimes_sqlids (sql_id) values ('2w6jm5gd7uz6r')
	into ca.elapsedtimes_sqlids (sql_id) values ('5jbz1pqy4yz7c')
	into ca.elapsedtimes_sqlids (sql_id) values ('amh12d19uz0k4')
	into ca.elapsedtimes_sqlids (sql_id) values ('5c0ucv5rn329u')
	into ca.elapsedtimes_sqlids (sql_id) values ('dx0303k5cm2nd')
	into ca.elapsedtimes_sqlids (sql_id) values ('bz75wtpd7g4dy')
	into ca.elapsedtimes_sqlids (sql_id) values ('asgqnuhdqb4vq')
	into ca.elapsedtimes_sqlids (sql_id) values ('06rd182sy35s1')
	into ca.elapsedtimes_sqlids (sql_id) values ('g8gnggzg3r6q0')
	into ca.elapsedtimes_sqlids (sql_id) values ('f5m48rfyrz6x2')
	into ca.elapsedtimes_sqlids (sql_id) values ('4yhv093f3b734')
	into ca.elapsedtimes_sqlids (sql_id) values ('cps56vhddr7a4')
	into ca.elapsedtimes_sqlids (sql_id) values ('9usf745ynr7j8')
	into ca.elapsedtimes_sqlids (sql_id) values ('70rx4vb60v7ym')
	into ca.elapsedtimes_sqlids (sql_id) values ('51rarf20gr8hd')
	into ca.elapsedtimes_sqlids (sql_id) values ('8m1ms9qb8g9q7')
	into ca.elapsedtimes_sqlids (sql_id) values ('0crzv7j81gat1')
	into ca.elapsedtimes_sqlids (sql_id) values ('g4vg2t6jsrawa')
	into ca.elapsedtimes_sqlids (sql_id) values ('93pd6z8cpgawu')
	into ca.elapsedtimes_sqlids (sql_id) values ('c9jrfkfbczc69')
	into ca.elapsedtimes_sqlids (sql_id) values ('24bgvmfpp3crv')
	into ca.elapsedtimes_sqlids (sql_id) values ('1zvj8nzw77hbf')
	into ca.elapsedtimes_sqlids (sql_id) values ('ad9d317093j99')
	into ca.elapsedtimes_sqlids (sql_id) values ('fvckqfr0fbjcu')
	into ca.elapsedtimes_sqlids (sql_id) values ('d84r4r86wzjj3')
	into ca.elapsedtimes_sqlids (sql_id) values ('0v79d9gqfzmh0')
	into ca.elapsedtimes_sqlids (sql_id) values ('3kc7d841k3ppb')
	into ca.elapsedtimes_sqlids (sql_id) values ('cx4z4c5ywrpzf')
	into ca.elapsedtimes_sqlids (sql_id) values ('9r20hnt1r7q03')
	into ca.elapsedtimes_sqlids (sql_id) values ('7xkztjf3cmrfh')
	into ca.elapsedtimes_sqlids (sql_id) values ('1s4q3zyq0brja')
	into ca.elapsedtimes_sqlids (sql_id) values ('fdk40xvkdzrza')
	into ca.elapsedtimes_sqlids (sql_id) values ('3y5xkzuu6zskh')
	into ca.elapsedtimes_sqlids (sql_id) values ('g8duf68tyzv8v')
	into ca.elapsedtimes_sqlids (sql_id) values ('4zfb6papzmwt6')
	into ca.elapsedtimes_sqlids (sql_id) values ('3atr6mrtx3xxq')
	into ca.elapsedtimes_sqlids (sql_id) values ('4qwj437karzkr')
	into ca.elapsedtimes_sqlids (sql_id) values ('d19dajrg2006b')
	into ca.elapsedtimes_sqlids (sql_id) values ('726rrup7ds0k8')
	into ca.elapsedtimes_sqlids (sql_id) values ('9mh5tuhb680pg')
	into ca.elapsedtimes_sqlids (sql_id) values ('56ahngwa300s6')
	into ca.elapsedtimes_sqlids (sql_id) values ('a5wu7j1xyw17q')
	into ca.elapsedtimes_sqlids (sql_id) values ('5nvs2cz8j01sb')
	into ca.elapsedtimes_sqlids (sql_id) values ('79mzk2ws4h23z')
	into ca.elapsedtimes_sqlids (sql_id) values ('43fx7bz6yw25m')
	into ca.elapsedtimes_sqlids (sql_id) values ('4z93sxdffw4vr')
	into ca.elapsedtimes_sqlids (sql_id) values ('gjhj2ggtks55f')
	into ca.elapsedtimes_sqlids (sql_id) values ('10punjdxg859n')
	into ca.elapsedtimes_sqlids (sql_id) values ('dr7c4nbtfs6ff')
	into ca.elapsedtimes_sqlids (sql_id) values ('7nnbzu3hf09wx')
	into ca.elapsedtimes_sqlids (sql_id) values ('2vz2yj0940b3b')
	into ca.elapsedtimes_sqlids (sql_id) values ('8fu1pc3g0hbbv')
	into ca.elapsedtimes_sqlids (sql_id) values ('03p7g7q9khbhk')
	into ca.elapsedtimes_sqlids (sql_id) values ('c9y8c37kwwcdv')
	into ca.elapsedtimes_sqlids (sql_id) values ('8pu9d1gncnd9g')
	into ca.elapsedtimes_sqlids (sql_id) values ('bqhtggxyw8dhp')
	into ca.elapsedtimes_sqlids (sql_id) values ('a3ybr46punfgs')
	into ca.elapsedtimes_sqlids (sql_id) values ('g5hkgx23h0gnx')
	into ca.elapsedtimes_sqlids (sql_id) values ('6wz9zqv4tsj92')
	into ca.elapsedtimes_sqlids (sql_id) values ('ga7d053cp8jf6')
	into ca.elapsedtimes_sqlids (sql_id) values ('b8q6ggu12cn16')
	into ca.elapsedtimes_sqlids (sql_id) values ('64b6a87jmwphj')
	into ca.elapsedtimes_sqlids (sql_id) values ('b3k108f0fwqxh')
	into ca.elapsedtimes_sqlids (sql_id) values ('bptr4ukb58rsm')
	into ca.elapsedtimes_sqlids (sql_id) values ('3y6cfr9z64rxh')
	into ca.elapsedtimes_sqlids (sql_id) values ('c1t442p204s0x')
	into ca.elapsedtimes_sqlids (sql_id) values ('1rakynu7k4s2s')
	into ca.elapsedtimes_sqlids (sql_id) values ('a5bcqhtjj0scv')
	into ca.elapsedtimes_sqlids (sql_id) values ('3yw6t8rbpcvd5')
	into ca.elapsedtimes_sqlids (sql_id) values ('4664gfzp4nwmp')
	into ca.elapsedtimes_sqlids (sql_id) values ('362829jk6nwvt')
	into ca.elapsedtimes_sqlids (sql_id) values ('ahh63kpb30wz2')
	into ca.elapsedtimes_sqlids (sql_id) values ('1kwv7dw8snxgm')
	into ca.elapsedtimes_sqlids (sql_id) values ('fpx3pk4nx8xsm')
	into ca.elapsedtimes_sqlids (sql_id) values ('3yrfvpwgg4xsz')
	into ca.elapsedtimes_sqlids (sql_id) values ('4j7hqp53wsz7t')
	into ca.elapsedtimes_sqlids (sql_id) values ('1cuvbjtxa8zv8')
	into ca.elapsedtimes_sqlids (sql_id) values ('aj18b7n47504c')
	into ca.elapsedtimes_sqlids (sql_id) values ('cm8mz2mk510jr')
	into ca.elapsedtimes_sqlids (sql_id) values ('1kya0nuq5p1bx')
	into ca.elapsedtimes_sqlids (sql_id) values ('gs59yhb0u51fp')
	into ca.elapsedtimes_sqlids (sql_id) values ('8bw1p78zu91k6')
	into ca.elapsedtimes_sqlids (sql_id) values ('f6h51mpbrj360')
	into ca.elapsedtimes_sqlids (sql_id) values ('2h4hpjn9qj3g3')
	into ca.elapsedtimes_sqlids (sql_id) values ('bp0r7392cd5fk')
	into ca.elapsedtimes_sqlids (sql_id) values ('axt52005k95zm')
	into ca.elapsedtimes_sqlids (sql_id) values ('5xays20baj79s')
	into ca.elapsedtimes_sqlids (sql_id) values ('djbf2pdh7j7qq')
	into ca.elapsedtimes_sqlids (sql_id) values ('36hq9ywz499u9')
	into ca.elapsedtimes_sqlids (sql_id) values ('7aprz2zvpjbsx')
	into ca.elapsedtimes_sqlids (sql_id) values ('26bj586y0tdhz')
	into ca.elapsedtimes_sqlids (sql_id) values ('b0c9s7tkbdf60')
	into ca.elapsedtimes_sqlids (sql_id) values ('07749664j5gb3')
	into ca.elapsedtimes_sqlids (sql_id) values ('8rq65qkztjgc5')
	into ca.elapsedtimes_sqlids (sql_id) values ('71160srp71gks')
	into ca.elapsedtimes_sqlids (sql_id) values ('c2aq2hz1b9h72')
	into ca.elapsedtimes_sqlids (sql_id) values ('76ugwwtpcxjhj')
	into ca.elapsedtimes_sqlids (sql_id) values ('52ascxcpz1jns')
	into ca.elapsedtimes_sqlids (sql_id) values ('1wnxrj7y7jmkc')
	into ca.elapsedtimes_sqlids (sql_id) values ('3a50x5sv21n6r')
	into ca.elapsedtimes_sqlids (sql_id) values ('g031uxwprjp9h')
	into ca.elapsedtimes_sqlids (sql_id) values ('b8ygrqr1fxpgr')
	into ca.elapsedtimes_sqlids (sql_id) values ('6h1ck3pkdpppr')
	into ca.elapsedtimes_sqlids (sql_id) values ('88hm779575ru3')
	into ca.elapsedtimes_sqlids (sql_id) values ('7stx12nptxsvp')
	into ca.elapsedtimes_sqlids (sql_id) values ('7kx96y5m01tr0')
	into ca.elapsedtimes_sqlids (sql_id) values ('1j133yyr6tttx')
	into ca.elapsedtimes_sqlids (sql_id) values ('8bc28kbryju8g')
	into ca.elapsedtimes_sqlids (sql_id) values ('9ryvpfcxbpwmu')
	into ca.elapsedtimes_sqlids (sql_id) values ('6gvhgnmxqxx12')
	into ca.elapsedtimes_sqlids (sql_id) values ('6sz5kabq2xx8s')
	into ca.elapsedtimes_sqlids (sql_id) values ('3vub89tgydxj9')
	into ca.elapsedtimes_sqlids (sql_id) values ('5bcq3r3245y0h')
	into ca.elapsedtimes_sqlids (sql_id) values ('cvqhdbzr4xyjs')
	into ca.elapsedtimes_sqlids (sql_id) values ('483k8cz9styzr')
	into ca.elapsedtimes_sqlids (sql_id) values ('36y2d7rf6pz25')
	into ca.elapsedtimes_sqlids (sql_id) values ('6w14v3nrfpz5a')
	into ca.elapsedtimes_sqlids (sql_id) values ('cfvjthwzupz9r')
	into ca.elapsedtimes_sqlids (sql_id) values ('1j7g74g6qxzth')
	into ca.elapsedtimes_sqlids (sql_id) values ('54ks146w9f124')
	into ca.elapsedtimes_sqlids (sql_id) values ('bc9rx8746f1uq')
	into ca.elapsedtimes_sqlids (sql_id) values ('fam4vjmphy3qp')
	into ca.elapsedtimes_sqlids (sql_id) values ('c17gys6292450')
	into ca.elapsedtimes_sqlids (sql_id) values ('cbafa8tdzy4y1')
	into ca.elapsedtimes_sqlids (sql_id) values ('9sj5260yuy5ay')
	into ca.elapsedtimes_sqlids (sql_id) values ('6n8vdyrk7f6ky')
	into ca.elapsedtimes_sqlids (sql_id) values ('ackys4b3tu783')
	into ca.elapsedtimes_sqlids (sql_id) values ('0qj8uhvzku7f6')
	into ca.elapsedtimes_sqlids (sql_id) values ('0frpk4xf5q7s7')
	into ca.elapsedtimes_sqlids (sql_id) values ('8fnmh6m47f8dz')
	into ca.elapsedtimes_sqlids (sql_id) values ('chqwx7cbqf8m2')
	into ca.elapsedtimes_sqlids (sql_id) values ('c37uhafdf290x')
	into ca.elapsedtimes_sqlids (sql_id) values ('a51xapquhu9w2')
	into ca.elapsedtimes_sqlids (sql_id) values ('0h6narussfb23')
	into ca.elapsedtimes_sqlids (sql_id) values ('59b8mcqz3accd')
	into ca.elapsedtimes_sqlids (sql_id) values ('574yudw56fcdn')
	into ca.elapsedtimes_sqlids (sql_id) values ('fpmbz0mgdudw4')
	into ca.elapsedtimes_sqlids (sql_id) values ('6j47b7xm5kf8b')
	into ca.elapsedtimes_sqlids (sql_id) values ('c3ruk0nfafg7b')
	into ca.elapsedtimes_sqlids (sql_id) values ('abfksxd18uhr8')
	into ca.elapsedtimes_sqlids (sql_id) values ('cbfmnbguyfkfx')
	into ca.elapsedtimes_sqlids (sql_id) values ('dfsbqqvnxup65')
	into ca.elapsedtimes_sqlids (sql_id) values ('4816j8cx8kt1q')
	into ca.elapsedtimes_sqlids (sql_id) values ('aqk73rp03ktz8')
	into ca.elapsedtimes_sqlids (sql_id) values ('9zw1nwssffuyx')
	into ca.elapsedtimes_sqlids (sql_id) values ('g25fr4nyvyw6h')
	into ca.elapsedtimes_sqlids (sql_id) values ('fch146f07yx6a')
	into ca.elapsedtimes_sqlids (sql_id) values ('2jhh6fqumyyhy')
	into ca.elapsedtimes_sqlids (sql_id) values ('925thzs9ayysa')
	into ca.elapsedtimes_sqlids (sql_id) values ('cpdu2q864kzhw')
	into ca.elapsedtimes_sqlids (sql_id) values ('2ta4ym403g01t')
	into ca.elapsedtimes_sqlids (sql_id) values ('5c5g7u2jkz1d2')
	into ca.elapsedtimes_sqlids (sql_id) values ('9wc1tud7qv21u')
	into ca.elapsedtimes_sqlids (sql_id) values ('72y4tg1yav2dh')
	into ca.elapsedtimes_sqlids (sql_id) values ('3896w6dvbv35t')
	into ca.elapsedtimes_sqlids (sql_id) values ('ahgj6kdtu3363')
	into ca.elapsedtimes_sqlids (sql_id) values ('82dnynzwd348v')
	into ca.elapsedtimes_sqlids (sql_id) values ('2s3rfzdr834d8')
	into ca.elapsedtimes_sqlids (sql_id) values ('5k128u2s3m576')
	into ca.elapsedtimes_sqlids (sql_id) values ('fmt62fc3yz5yq')
	into ca.elapsedtimes_sqlids (sql_id) values ('gzdy5gktyr6hm')
	into ca.elapsedtimes_sqlids (sql_id) values ('ba0ws9u20z6rk')
	into ca.elapsedtimes_sqlids (sql_id) values ('bpyvuqdf0v878')
	into ca.elapsedtimes_sqlids (sql_id) values ('f12vh5yqgg87a')
	into ca.elapsedtimes_sqlids (sql_id) values ('a8xrcgb3sg8d4')
	into ca.elapsedtimes_sqlids (sql_id) values ('djrzzmtu6g8yv')
	into ca.elapsedtimes_sqlids (sql_id) values ('12w8pxvjsra6v')
	into ca.elapsedtimes_sqlids (sql_id) values ('bbnafz81gvamn')
	into ca.elapsedtimes_sqlids (sql_id) values ('g9sp79w503cpd')
	into ca.elapsedtimes_sqlids (sql_id) values ('70kk0f6thbd22')
	into ca.elapsedtimes_sqlids (sql_id) values ('6qdrmjzrgrdf1')
	into ca.elapsedtimes_sqlids (sql_id) values ('73u1yrx5rbdvk')
	into ca.elapsedtimes_sqlids (sql_id) values ('9szvcrzhwzfqr')
	into ca.elapsedtimes_sqlids (sql_id) values ('0p2k4qv4ubfwy')
	into ca.elapsedtimes_sqlids (sql_id) values ('42b0h777azhd0')
	into ca.elapsedtimes_sqlids (sql_id) values ('0ksvwvrxwzju8')
	into ca.elapsedtimes_sqlids (sql_id) values ('gn25ncht2mkss')
	into ca.elapsedtimes_sqlids (sql_id) values ('c671j9u0fzmga')
	into ca.elapsedtimes_sqlids (sql_id) values ('4p6hxtu33vprk')
	into ca.elapsedtimes_sqlids (sql_id) values ('7kn78dbmmrpvp')
	into ca.elapsedtimes_sqlids (sql_id) values ('8r2k9bf84rpy3')
	into ca.elapsedtimes_sqlids (sql_id) values ('bpyv2mrwfvrta')
	into ca.elapsedtimes_sqlids (sql_id) values ('126wss8m3bs96')
	into ca.elapsedtimes_sqlids (sql_id) values ('9xpc5t7v5ztxm')
	into ca.elapsedtimes_sqlids (sql_id) values ('d6vbnm93j7u25')
	into ca.elapsedtimes_sqlids (sql_id) values ('4nuxk1rmm7v2y')
	into ca.elapsedtimes_sqlids (sql_id) values ('arhqcj1uxgv39')
	into ca.elapsedtimes_sqlids (sql_id) values ('cm5msx5ztvv77')
	into ca.elapsedtimes_sqlids (sql_id) values ('gjqmqmjyq3vwh')
	into ca.elapsedtimes_sqlids (sql_id) values ('0xmh772t6rygy')
select * from dual;
commit;
@celapsedtimes_sqlids

*/