
--check if account exists
SELECT USERNAME FROM dba_users WHERE USERNAME = 'ATOSSVC' /*TASK779583*/;

-- creates your account
CREATE USER ATOSSVC
	IDENTIFIED BY "PutYourPasswordHere"
	DEFAULT TABLESPACE USERS
	TEMPORARY TABLESPACE TEMP
	PROFILE PLEXUS_SVC
	ACCOUNT UNLOCK /*TASK779583*/;

-- grant permissions
GRANT CREATE SESSION TO ATOSSVC /*TASK779583*/;
GRANT SELECT ON PRODDTA.F5541043 TO ATOSSVC /*TASK779583*/;




