
  CREATE OR REPLACE EDITIONABLE PROCEDURE "PRODDTA"."P_F5542650_PRCFLG_UPDATE"
AS
BEGIN
	UPDATE PRODDTA.F5542650
	SET TS$PRCFLG = 'N'
	WHERE
		TRIM(TSQC04) || TRIM(TSQC05) || TRIM(TSQC06) || TRIM(TSQC07) || TRIM(TSQC08) = 'PASSEDPASSEDCOMPLETEPASSEDPASSED'
		AND TS$PRCFLG = 'Y'
		AND TS$RSP = 'S'
		AND TRIM(TSMCU) || TRIM(TSDOCO) || TRIM(TSDCTO) || TRIM(TSLNID) || TRIM(TSNXTR) IN (
			SELECT TRIM(SDMCU) || TRIM(SDDOCO) || TRIM(SDDCTO) || TRIM(SDLNID) || TRIM(SDNXTR)
			FROM PRODDTA.F4211
			WHERE SDNXTR = '560'
		);

	COMMIT;

EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('Error Code: ' || SQLCODE);
		DBMS_OUTPUT.PUT_LINE('Error Message: ' || SQLERRM);
		RAISE;
END;
/
