


  CREATE TABLE "PRODDTA"."F574211"
   (    "SDEDOC" NUMBER,
        "SDKCOO" CHAR(5),
        "SDDOCO" NUMBER,
        "SDDCTO" CHAR(2),
        "SDLNID" NUMBER,
        "SDMCU" CHAR(12),
        "SDCPIL" CHAR(25),
        "SDTRQT" NUMBER,
        "SDLOCN" CHAR(20),
        "SDLOTN" CHAR(30),
        "SDLPNU" CHAR(40),
        "SDEDSP" CHAR(1),
        "SDURCD" CHAR(2),
        "SDURRF" CHAR(15),
        "SDURAB" NUMBER,
        "SDURAT" NUMBER,
        "SDURDT" NUMBER(6,0),
        "SDUSER" CHAR(10),
        "SDPID" CHAR(10),
        "SDJOBN" CHAR(10),
        "SDUPMJ" NUMBER(6,0),
        "SDUPMT" NUMBER,
        "SDERRM" CHAR(80),
        "SDSORCID" NUMBER,
        "SD57UKID" CHAR(25)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "PRODDTAT";
  CREATE UNIQUE INDEX "PRODDTA"."F574211_0" ON "PRODDTA"."F574211" ("SD57UKID", "SDKCOO", "SDDOCO", "SDDCTO", "SDLNID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS COMPRESS ADVANCED LOW
  TABLESPACE "PRODDTAI";
ALTER TABLE "PRODDTA"."F574211" ADD CONSTRAINT "F574211_PK" PRIMARY KEY ("SD57UKID", "SDKCOO", "SDDOCO", "SDDCTO", "SDLNID")
  USING INDEX "PRODDTA"."F574211_0"  ENABLE;


  CREATE INDEX "PRODDTA"."F574211_2" ON "PRODDTA"."F574211" ("SDSORCID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS COMPRESS ADVANCED LOW
  TABLESPACE "PRODDTAI" ;


  CREATE INDEX "PRODDTA"."F574211_3" ON "PRODDTA"."F574211" ("SD57UKID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS COMPRESS ADVANCED LOW
  TABLESPACE "PRODDTAI" ;

insert into proddta.F574211 (SDEDOC,SDKCOO,SDDOCO,SDDCTO,SDLNID,SDMCU,SDCPIL,SDTRQT,SDLOCN,SDLOTN,SDLPNU,SDEDSP,SDURCD,SDURRF,SDURAB,SDURAT,SDURDT,SDUSER,SDPID,SDJOBN,SDUPMJ,SDUPMT,SDERRM,SDSORCID,SD57UKID)
select SDEDOC,SDKCOO,SDDOCO,SDDCTO,SDLNID,SDMCU,SDCPIL,SDTRQT,SDLOCN,SDLOTN,SDLPNU,SDEDSP,SDURCD,SDURRF,SDURAB,SDURAT,SDURDT,SDUSER,SDPID,SDJOBN,SDUPMJ,SDUPMT,SDERRM,SDSORCID,to_char(SD57UKID) from savedata;